- Sources/AppDelegate.swift
Just a small thing I found while exploring the codebase 👍
> Fixed wrong tab indentation

- .travis.yml
- Readme.md
> Update Travis credentials and links to point to the OSS version

- Sources/Controllers/Settings/DynamicSettingCategoryViewController.swift
This was mostly an exercise in using `guard`, `map` and `filter` instead of `if let` and for loops. Do you think it is more readable @colinta?
> refactor toggleSetting()

- Readme.md
Super awesome job // Congrats on open-sourcing! Can't wait to really dive-in and check it out. (Feel free to ignore my trivial readme correction). 😎
> My OCD is forcing me to correct a typo

- Sources/AppDelegate.swift
- Sources/Controllers/Profile/ProfileHeaderCellSizeCalculator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Profile/ProfileViewController.xib
- Sources/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/StreamKind.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Profile/ProfileViewControllerSpec.swift
- Specs/Controllers/Stream/StreamKindSpec.swift
We need to get a TestFlight build of this for sure, to make sure Product gives it the OK.
> Implements the Grid/List toggle on profiles

- Resources/StubbedResponses/profile_available_user_profile_toggles.json
- Sources/Controllers/Settings/DynamicSettingCategoryViewController.swift
- Sources/Model/DynamicSetting.swift
- Sources/Model/Profile.swift
- Sources/Model/User.swift
- Specs/Controllers/Settings/DynamicSettingCellPresenterSpec.swift
- Specs/Controllers/Settings/DynamicSettingCellSpec.swift
- Specs/Extensions/StringExtensionSpec.swift
- Specs/Model/DynamicSettingsSpec.swift
Adds `setsAnother` property, updates settings before sending the request.
> Implements the "setting one setting sets another setting" feature.

- .swiftlint.yml
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/Cells/StreamFooterButton.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamLoadingCell.swift
- Sources/Controllers/Stream/Cells/StreamNotificationCellSizeCalculator.swift
- Sources/Controllers/Stream/Cells/StreamTextCellSizeCalculator.swift
- Sources/Controllers/Stream/StreamCollectionViewLayout.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Extensions/ImageExtensions.swift
- Sources/Styling/ElloAttributedString.swift
- Sources/Utilities/Tag.swift
- Sources/Views/CreateCommentBackgroundView.swift
- Sources/Views/ElloPullToRefreshView.swift
The following rules were added and fixed:
control_statement
legacy_constant
legacy_constructor
variable_name_max_length
> Adds a few more Swiftlint rules

- .travis.yml
So our Travis log is manageable.
> Make 'pod repo update' silent

- .travis.yml
- Readme.md
> Updating the name of "APNS Pusher" to "Knuff" in Readme.

- Sources/Model/CategoryList.swift
Separate PR just to make sure specs are still green.
> These 'hardCodedPrimaries' are not used any more

- Sources/Controllers/Stream/CellDequeing/StreamHeaderCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Model/Category.swift
- Sources/Model/JSONAble.swift
- Specs/Controllers/Stream/CellDequeing/StreamHeaderCellPresenterSpec.swift
- Specs/Helpers/Stubs.swift
Added specs for this in `StreamHeaderCellPresenterSpec`
> Show the post category in grid view

- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
- Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/StreamTextCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamTextCellSizeCalculator.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
Replace `if let _ = a as? B` with `if a is B`
> Swift refactor

- Sources/Controllers/Discover/DiscoverViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/Tracker.swift
- Specs/Helpers/SpecsTrackingAgent.swift
Adds `category.name` to the `DiscoverViewController` screen appeared tracking event.
> Track categories, and some refactors

- Sources/AppDelegate.swift
- Sources/Networking/CategoryService.swift
> Don't cache categories, but DO cache category images at startup

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Stream/Cells/CategoryListCell.swift
- Sources/Networking/ElloAPI.swift
- Sources/Networking/ElloProvider.swift
- Specs/Controllers/Stream/Cells/CategoryListCellSpec.swift
> Updates the CategoryListCell UI

- Sources/Controllers/Stream/StreamKind.swift
The issue was that comments were getting filtered out!
> Fixes commenting in Discover

- Sources/Controllers/Profile/ProfileViewController.swift
- cover image occlusion [Fixes #126324367]
- sharing on ipad [Fixes #126324373]
> Fixes two iPad bugs in 1.9

- Sources/Controllers/Profile/ProfileHeaderCell.swift
- Sources/Controllers/Profile/ProfileHeaderCell.xib
- Sources/Controllers/Profile/ProfileViewController.swift
> Fixes avatarImage frame and the top position of "white solid view"

- Sources/Controllers/Stream/StreamKind.swift
- Specs/Controllers/Stream/StreamDataSourceSpec.swift
- Specs/Controllers/Stream/StreamKindSpec.swift
We added 3 cells, so change `1` to `4`.
Magic numbers == 😢
> Fixes insertion point in Profile when creating a post

- Ello.xcodeproj/project.pbxproj
- ShareExtension/ElloAPISharingHeaders.swift
- Sources/Networking/ElloAPI.swift
- Sources/Networking/ElloAPISharingHeaders.swift
I think the number of lines added and removed is approximately equal to how many months ago the story was created.
*Progress!*
> Attach a custom tracking event when a post is created via the ShareExtension

- Ello.xcodeproj/project.pbxproj
- ShareExtension/Info.plist
- Support/Info.plist
Adds `1.9.1` tag, sets build and app version, sets and reverts bundle id.
> 1.9.1 Release

- Sources/Model/Regions/RegionParser.swift
- Sources/model/Regions/RegionKind.swift
- Sources/model/Regions/RegionKindStreamCellTypeAddition.swift
Removes the `AffiliateImage` type
> Don't need these any more!

- Ello.xcodeproj/project.pbxproj
- Sources/Model/ElloKeychain.swift
- Specs/Utilities/ElloKeychainSpec.swift
Refactors `ElloKeychain.swift` to allow resetting, and adds specs.
> Resolves #79

- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/App/DebugTodoController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Networking/ElloURI.swift
Fixes https://www.pivotaltracker.com/story/show/127242389
> Adds support for opening Category from a post URL

- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Model/Tracker.swift
> Add Segment tracking for buy button clicks

- Sources/Controllers/Stream/StreamKind.swift
- Specs/Controllers/Stream/StreamKindSpec.swift
> Don't store grid/list pref per user, store globally

- Sources/Controllers/Relationship/RelationshipControl.swift
- Sources/Controllers/Relationship/RelationshipController.swift
- Sources/Model/Relationship.swift
- Sources/Networking/RelationshipService.swift
The new relationship was not being stored properly, so the "immediate UI update" wasn't working.
> Fixes Following/Starred

- Sources/Model/Regions/ImageRegion.swift
> Decode ImageRegion.alt as an optional

- Sources/Utilities/InterfaceString.swift
Follow or mention them to help them get started!
> Updating Profile zero state

- Sources/Controllers/Drawer/DrawerViewDataSource.swift
go to `/wtf/` instead of `/wtf/help/the-basics/`
> Fixes 404 in drawer

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Profile/ProfileViewController.xib
- Sources/Controllers/Stream/CellDequeing/NoPostsCellPresenter.swift
- Sources/Controllers/Stream/Cells/NoPostsCell.swift
- Sources/Controllers/Stream/Cells/NoPostsCell.xib
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Controllers/Stream/StreamGenerator.swift
- Specs/Controllers/Profile/ProfileGeneratorSpec.swift
- Specs/Controllers/Stream/Detail/PostDetailGeneratorSpec.swift
Replaces 'noPostsView' in ProfileViewController with a 'NoPostsCell' (StreamCellItem)
> Implements updated "No Posts" view.

- ShareExtension/Info.plist
- Support/Info.plist
This PR will grow as the 1.14 PRs get merged into `next/1.14.0`.  It's just a "catch all" branch/PR.
> Version 1.14

- .travis.yml
> Wire up Danger

- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/Stream/CellDequeing/UserAvatarsCellPresenter.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
This functionality was lost with the generators.
> Restores "see all" button functionality on a post detail's lovers and reposters

- Sources/Controllers/Stream/StreamViewController.swift
Hopefully [fixes #130201849](https://www.pivotaltracker.com/story/show/130201849)
> Ensure readiness for comment updates

- Resources/StubbedResponses/users_user_details.json
- Sources/Model/User.swift
- Specs/Model/UserSpec.swift
@Justin-Holmes Can you verify my JSON and local names are correct?  The JSON should match the server, and the local name should be the camel-cased version.
> Adds notifyOfWatchesViaPush, notifyOfWatchesViaEmail user settings

- Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
- Sources/Controllers/Onboarding/CreateProfileViewController.swift
- Sources/Controllers/Onboarding/InviteFriendsViewController.swift
- Sources/Controllers/Onboarding/OnboardingProtocols.swift
- Sources/Controllers/Onboarding/OnboardingScreen.swift
- Sources/Controllers/Onboarding/OnboardingViewController.swift
So that choosing categories is required.
> Replaces 'isLastOnboardingStep' with 'hasAbortButton' and updates the logic there

- Podfile
- Podfile.lock
- ShareExtension/ShareViewController.swift
- Sources/Controllers/Drawer/DrawerViewDataSource.swift
- Sources/Controllers/Stream/StreamContainerViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/InterfaceString.swift
- Sources/Views/PulsingCircle.swift
A bit of background:
After waiting what seemed like **_days_** for the app to compile I started doing some research on additional compile speed improvements. Robert Gummesson has a g 2 part writeup on [some compile speed optimizations](https://medium.com/swift-programming/swift-build-time-optimizations-part-2-37b0a7514cbe#.aa27wackp) as well as a tool called [Build Time Analyzer for Xcode](https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode) for checking the compile times. 
I found a few easy to optimize chunks of code and dropped my compile time from over 9 minutes to close 4 minutes. Your mileage may vary.
> Make Compiling Great Again

- Sources/AppDelegate.swift
- Sources/Controllers/App/DebugTodoController.swift
- Sources/Networking/AnonymousAuthService.swift
- Sources/Networking/AuthToken.swift
- Sources/Networking/CredentialsAuthService.swift
- Sources/Networking/ProfileService.swift
- Sources/Networking/ReAuthService.swift
- Sources/Utilities/FreeMethods.swift
As part of trying to figure out the push notifications, I rewrote our `log` method.  Seems handy to have custom logs visible in debug builds, so I figured I'd put it in a PR!
Also: removes the logging of tokens, since we haven't had log out issues in a long time.
> Implements new logging methods

- Podfile
- Podfile.lock
- Sources/Controllers/Relationship/RelationshipControl.swift
Dunno how the backgroundColor used to be set automatically, but I guess a change to RoundedElloButton is the culprit.
> Fixes the button styling to support fast update

- Ello.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- Resources/StubbedResponses/CustomResponses/watches_creating_a_watch.json
- Sources/Model/Activity.swift
- Sources/Model/Notification.swift
- Sources/Model/NotificationAttributedTitle.swift
- Sources/Model/Post.swift
- Sources/Model/Protocols/Authorable.swift
- Sources/Model/Protocols/Groupable.swift
- Sources/Model/Protocols/PostActionable.swift
- Sources/Model/Watch.swift
- Sources/Networking/MappingType.swift
- Sources/Utilities/CrashlyticsKey.swift
- Specs/Model/NotificationAttributedTitleSpec.swift
- Specs/Model/WatchSpec.swift
- adds the watch-post notifications types to `Activity`
- displays them similarly as loves
- to share some code w/ loves, I added the `PostActionable` protocol, implemented by `Love` and `Watch`
> Watch post notifications

- Resources/StubbedResponses/CustomResponses/watches_creating_a_watch.json
- Specs/Helpers/Stubs.swift
- Specs/Model/WatchSpec.swift
- Specs/QuickExtensions.swift
> Some fixes to specs because of Watch class

- Resources/StubbedResponses/users_user_details.json
- Sources/Model/User.swift
- Specs/Model/UserSpec.swift
> Adds notifyOfCommentsOnPostWatchViaPush and notifyOfCommentsOnPostWatchViaEmail to User settings

- .travis.yml
Rebasing a base branch after it had been branched created mayhem. Bad Sean. This reintroduces a missing commit. Thanks @colinta 🙏
> Updates travis xcodebuild run to use iOS 10

- Sources/Controllers/Onboarding/CreateProfileViewController.swift
- Sources/Model/Tracker.swift
@Justin-Holmes  pointed these out.
> Was missing 'uploaded avatar/coverImage' events

- Sources/Model/Activity.swift
- Sources/Model/NotificationAttributedTitle.swift
And adds the here-to-fore missing `watch_comment_notification` text.
> Fixes the Watch notification text

- Sources/Controllers/Onboarding/InviteFriendsViewController.swift
- Sources/Controllers/Stream/CellDequeing/StreamInviteFriendsCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/Cells/StreamInviteFriendsCell.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/Tracker.swift
We had a generic tracking event, need a specific one for onboarding
CC @Justin-Holmes
> Adds 'invited friend during onboarding' tracking event

- Sources/Controllers/Profile/Calculators/ProfileBioSizeCalculator.swift
- Sources/Controllers/Profile/Calculators/ProfileHeaderCellSizeCalculator.swift
- Sources/Controllers/Profile/ProfileHeaderCell.swift
- Sources/Controllers/Profile/Views/ProfileBioView.swift
- Sources/Controllers/Profile/Views/ProfileLinksView.swift
- Sources/Controllers/Profile/Views/ProfileNamesView.swift
- Sources/Controllers/Profile/Views/ProfileStatsView.swift
- Sources/Controllers/Stream/CalculatedCellHeights.swift
- Sources/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenter.swift
Resize bio on rotation, and make backgrounds white on all profile views
> Fixes for ipad

- Sources/Controllers/Profile/Calculators/ProfileBioSizeCalculator.swift
- Sources/Controllers/Profile/Calculators/ProfileLinksSizeCalculator.swift
- Sources/Controllers/Profile/Views/ProfileBioView.swift
- Sources/Controllers/Profile/Views/ProfileStatsView.swift
- Sources/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenter.swift
- Specs/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenterSpec.swift
- Specs/Controllers/Stream/ProfileBioSizeCalculatorSpec.swift
- Specs/Controllers/Stream/ProfileLinksSizeCalculatorSpec.swift
Hide the bio or links if they're empty, and hide the gray lines appropriately.
> Empty bio / links

- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Profile/Views/ProfileTotalCountView.swift
- Sources/Controllers/Stream/CellDequeing/ProfileTotalCountPresenter.swift
- Specs/Controllers/Stream/CellDequeing/ProfileTotalCountPresenterSpec.swift
- Specs/Helpers/Stubs.swift
The featured Category badge displays when a user is included in one or more categories.
> Uses a user’s actual categories

- Resources/www/index.html
- Sources/Controllers/Stream/CellDequeing/StreamTextCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamTextCell.swift
- Sources/Controllers/Stream/Cells/StreamTextCellSizeCalculator.swift
- Sources/Extensions/UIWebView.swift
Sizing w/ multiple columns, and overlapping image/text.  Though, TBH, not entirely sure *why* that is fixed now.
> Fixes to `StreamTextCell`

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Categories/CategoryScreen.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Stream/CellDequeing/PagePromotionalHeaderCellPresenter.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/PagePromotional.swift
- Sources/Networking/ElloAPI.swift
- Sources/Networking/ElloAPIDescription.swift
- Sources/Networking/MappingType.swift
- Sources/Networking/PagePromotionalService.swift
- Sources/Utilities/Preloader.swift
If the `Category` handed to `CategoryViewController` is a `level == .Meta` category, the `page_promotionals` endpoint will be fetched, and a random promotional will be selected as the "primary jsonable" for the category.
New cell type `PagePromotionalHeader`, and renamed `CategoryHeader` to `CategoryPromotionalHeader`.
> Implements `PagePromotional`s

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Stream/CellDequeing/CategoryHeaderCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/PagePromotionalHeaderCellPresenter.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCellSizeCalculator.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Extensions/NSAttributedStringExtensions.swift
- Sources/Model/Category.swift
- Specs/Controllers/Stream/CategoryHeaderCellSizeCalculatorSpec.swift
- Specs/Helpers/Stubs.swift
Also some misc spec compile fixes, and refactored the `categoryIsMeta` code (moved it into `Category`).
> Implements CategoryHeaderCellSizeCalculator w/ specs

- Sources/Controllers/Stream/StreamCellItemParser.swift
- Sources/Controllers/Stream/StreamKind.swift
- Specs/Controllers/Profile/ProfileViewControllerSpec.swift
- Specs/Controllers/Stream/StreamCellItemParserSpec.swift
- Specs/Controllers/Stream/StreamKindSpec.swift
> Removes post headers from user streams

- Sources/Controllers/Categories/CategoryGenerator.swift
- Specs/Controllers/Categories/CategoryGeneratorSpec.swift
And test for categories in the testing mock option.
> Updates the CategoryGeneratorSpec to use CategoryStreamDestination

- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/StreamDataSource.swift
Call to Action and posted/sponsored by buttons link correctly.
> Wire up category header buttons

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Categories/CategoryProtocols.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Discover/DiscoverAllCategoriesViewController.swift
- Sources/Model/Category.swift
- Sources/Model/CategoryLevel.swift
- Sources/Networking/ElloAPI.swift
- Specs/Controllers/Categories/CategoryViewControllerSpec.swift
- Specs/Controllers/Discover/DiscoverAllCategoriesViewControllerSpec.swift
- Specs/Controllers/Profile/ProfileCategoriesScreenSpec.swift
- Specs/Helpers/Stubs.swift
- Specs/Model/CategoryListSpec.swift
- Specs/Model/CategorySpec.swift
This PR looks for 'meta' categories, but if none come back from the server, it falls back to the 'internal' meta category objects.
> Adds support for 'meta' categories, but doesn't require them.

- Sources/Controllers/Categories/CategoryProtocols.swift
- Sources/Controllers/Categories/CategoryScreen.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Profile/ProfileProtocols.swift
- Sources/Controllers/Profile/ProfileScreen.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Search/SearchScreen.swift
- Sources/Controllers/Search/SearchViewController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Controllers/Stream/AddFriendsViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Specs/Controllers/Categories/CategoryViewControllerSpec.swift
- Specs/Controllers/Search/SearchViewControllerSpec.swift
update Search, Profile, and Category with new logic.
> Refactor the 'updateInsets' helper to always set 'topInset' according to the 'nav bar' (which is often a button container)

- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/AmazonCredentials.swift
And found the "weird animating navigation bar items" animation bug.
> Fixes AmazonCredentials (and, therefore, uploading)

- Sources/Controllers/Onboarding/InviteFriendsViewController.swift
Fixes the onboarding/invite friends bug
> Don't change all cell item types, only .InviteFriends

- Ello.xcodeproj/project.pbxproj
- ShareExtension/Info.plist
- Specs/Info.plist
- Support/Info.plist
Once we go live, this can be tagged and merged.
> 1.18.0 release

- Sources/Views/CategoryCardView.swift
Quick fix: I noticed images were being stretched in the category cards.
> Fixes content mode on category card views

- fastlane/Fastfile
beta lane now switches to prod keys before compiling
> Updates to Fastfile

- Sources/Controllers/Alerts/AlertCell.swift
- Sources/Controllers/Alerts/AlertViewController.swift
- Sources/Controllers/AutoComplete/AutoCompleteCell.swift
- Sources/Controllers/AutoComplete/AutoCompleteCellPresenter.swift
- Sources/Controllers/AutoComplete/AutoCompleteDataSource.swift
- Sources/Controllers/AutoComplete/AutoCompleteViewController.swift
- Sources/Controllers/Drawer/DrawerCell.swift
- Sources/Controllers/Drawer/DrawerViewController.swift
- Sources/Controllers/Drawer/DrawerViewDataSource.swift
- Sources/Controllers/Hire/HireScreen.swift
- Sources/Controllers/Omnibar/OmnibarErrorCell.swift
- Sources/Controllers/Omnibar/OmnibarImageCell.swift
- Sources/Controllers/Omnibar/OmnibarImageDownloadCell.swift
- Sources/Controllers/Omnibar/OmnibarRegion.swift
- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
- Sources/Controllers/Omnibar/OmnibarTextCell.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Model/AutoCompleteResult.swift
- Sources/Utilities/FreeMethods.swift
- Sources/Views/AvatarButton.swift
- Sources/Views/ElloTextField.swift
- Sources/controllers/Alerts/AlertViewControllerKeyboardExtension.swift
- Specs/Controllers/AutoComplete/AutoCompleteViewControllerSpec.swift
- Specs/Controllers/Drawer/DrawerViewControllerSpec.swift
Updates from Lucian: the autocomplete view moves to the keyboard, the text field is always visible, "location pin" is displayed in the text field and in autocomplete results.
> Fixes to Location Settings (for 1.19)

- Sources/Controllers/Stream/StreamContainerViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/InterfaceString.swift
1. Remove legacy following/starred no results text
1. Reassign empty stream cell on grid/list toggle
> Tweaks to the new zero states

- Sources/Controllers/Settings/CredentialSettingsViewController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
> Fixes settings

- Sources/Controllers/Notifications/NotificationsGenerator.swift
- Sources/Networking/NewContentService.swift
> Fixes from PR review

- Sources/Controllers/AutoComplete/AutoCompleteCell.swift
- Sources/Controllers/Drawer/DrawerCell.swift
- Sources/Networking/ElloURI.swift
- Specs/Networking/ElloURISpec.swift
[fixes #134104237](https://www.pivotaltracker.com/story/show/134104237)
> Fixes internal ninja links in announcement push notifications

- Ello.xcworkspace/xcshareddata/Ello.xcscmblueprint
- Podfile
- Podfile.lock
- Sources/Controllers/Onboarding/CreateProfileProtocols.swift
- Sources/Controllers/Onboarding/CreateProfileScreen.swift
- Sources/Controllers/Onboarding/CreateProfileViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Extensions/UIImagePickerController.swift
- Specs/Controllers/Onboarding/CreateProfileScreenSpec.swift
- Specs/Controllers/Onboarding/CreateProfileViewControllerSpec.swift
- Specs/ShareExtension/ShareAttachmentProcessorSpec.swift
In addition, a few swifty changes.
> Use Ello's ImagePickerSheetController

- Sources/Controllers/Notifications/AnnouncementCell.swift
- Sources/Controllers/Stream/Calculators/AnnouncementCellSizeCalculator.swift
- Sources/Model/Announcement.swift
- white line at the top of the cell
- image aspect ratio
- if the image is taller than the text, the cell size will be increased to accomodate.
> Fixes to Announcements UI

- Sources/Controllers/Notifications/AnnouncementCell.swift
- Sources/Controllers/Notifications/NotificationsViewController.swift
- Sources/Controllers/Stream/Calculators/AnnouncementCellSizeCalculator.swift
- Sources/Model/Announcement.swift
- Sources/Networking/ElloURI.swift
- Specs/Networking/ElloURISpec.swift
Updates the announcements and tracking changes in 1.20 to swift 3.
> Merges recent work on 1.20 into swift3

- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Discover/DiscoverAllCategoriesViewController.swift
- Sources/Controllers/Notifications/NotificationsGenerator.swift
- Sources/Controllers/Notifications/NotificationsViewController.swift
- Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
- Sources/Controllers/Onboarding/CreateProfileViewController.swift
- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/StreamViewController.swift
Conversion was a PITA, but *yay* swift 3 syntax.
> Changes 'sself' and 'weakSelf' and 'wSelf' to `self`/self

- Sources/Controllers/Settings/SettingsViewController.swift
[Fixes #137191751](https://www.pivotaltracker.com/story/show/137191751)
> Hides checkmark on location when empty

- Ello.xcodeproj/project.pbxproj
- ShareExtension/Info.plist
- Specs/Info.plist
- Support/Info.plist
Fixes the spinners on post detail and category, so that we never show two spinners.
> 1.20 build 5594

- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/StreamViewControllerSpec.swift
> Last minute spinner fixes

- Ello.xcodeproj/project.pbxproj
- ShareExtension/Info.plist
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/StreamViewControllerSpec.swift
- Specs/Info.plist
- Support/Info.plist
Last one, we're sure this time :wink:
> 1.20 build 5604

- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
Terrible, just terrible :smiley:
I like this spinner show/hide/insert logic, though, it finally feels simple and correct and consistent.
> Fixes the spinners again, and more importantly the strange Notifications hiding bug

- Sources/Networking/PostService.swift
`loadedFromPostId` was never set in PostService.loadComments
> Fixes the "tapping on reply does nothing" bug

- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Networking/PostEditingService.swift
> Support commenting on a post via deep-linking when the comment points to a repost that hasn't been loaded

- Podfile
- Podfile.lock
- Specs/Controllers/Omnibar/OmnibarViewControllerSpec.swift
- Specs/Controllers/Stream/PostbarControllerSpec.swift
Also updates Nimble with the hopes of unclogging Travis
> Fixes spec compile errors

- Resources/Settings.storyboard
- Sources/Controllers/Settings/CredentialSettingsViewController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
Also sets all the keyboards' appearances to `.dark`.
> Resolves #137191691; fixes scrolling behavior in Settings

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/App/DebugController.swift
- Sources/Controllers/App/DebugImageUploadController.swift
- Sources/Environment/AppSetup.swift
- Sources/Extensions/NumberExtensions.swift
- Sources/Networking/S3UploadingService.swift
- Specs/Environment/AppSetupSpec.swift
- Specs/Extensions/NumberExtensionsSpec.swift
[Finishes #137031547](https://www.pivotaltracker.com/story/show/137031547)
> Adds ability to adjust upload image quality

- Sources/Controllers/Stream/StreamDataSource.swift
By not assigning new/updated post to comment cells.
> Fixes 'Create Comment Cell' button

- Sources/Controllers/Search/SearchScreen.swift
- Sources/Controllers/Search/SearchViewController.swift
- Sources/Controllers/Stream/AddFriendsViewController.swift
- Sources/Networking/Mapper.swift
> Hides Search Screen when logged out

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/App/DebugController.swift
- Sources/Utilities/AppDefaults.swift
- Sources/Utilities/Defaults.swift
- Specs/Utilities/GroupDefaultsSpec.swift
@steam I copied `logOutCurrentUser()` and then kept the parts I thought were appropriate (not many).
> Bust the cache on login

- Sources/Controllers/Stream/Cells/StreamFooterCell.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Controllers/Stream/Cells/StreamTextCell.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
Part 2 of the responder chain conversion with some `guard` hotness thrown in for good measure.
> StreamEditingDelegate becomes StreamEditingResponder

- Sources/Controllers/Notifications/NotificationCell.swift
- Sources/Controllers/Notifications/NotificationsViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/PostbarControllerSpec.swift
- Specs/Controllers/Stream/StreamViewControllerSpec.swift
> NotificationDelegate becomes NotificationResponder

- Sources/Controllers/Notifications/AnnouncementCell.swift
- Sources/Controllers/Notifications/NotificationsViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
Small one combining both Announcement responder conversions.
> Announcement delegates -> responders

- Sources/Controllers/Notifications/NotificationCell.swift
- Sources/Controllers/Profile/ProfileHeaderCell.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamTextCell.swift
- Sources/Controllers/Stream/Cells/UserAvatarsCell.swift
- Sources/Controllers/Stream/Cells/UserListItemCell.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/StreamViewControllerSpec.swift
> UserDelegate -> UserResponder

- Sources/Controllers/Stream/Cells/CategoryListCell.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/Cells/CategoryListCellSpec.swift
- Specs/QuickExtensions.swift
Pretty small, needed to modify the Quick `showView` helper.
> CategoryListCellDelegate -> CategoryListCellResponder

- Sources/Controllers/Categories/CategoryGenerator.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Networking/ElloManager.swift
So this is how we could add a timeout to our API requests.  @caseydoran @steam does this sound like a good idea to you?
> Just a thought, but on staging I was 'locked out' due to a long API request

- Sources/Controllers/Onboarding/InviteFriendsViewController.swift
- Sources/Controllers/Stream/Cells/SearchStreamCell.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
> SearchStreamDelegate -> SearchStreamResponder

- Sources/Controllers/Alerts/AlertCell.swift
- Sources/Controllers/Alerts/AlertViewController.swift
> AlertCellDelegate -> AlertCellResponder

- Sources/Controllers/Stream/StreamContainerViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
> UserTappedDelegate -> UserTappedResponder

- Sources/Controllers/Stream/CellDequeing/StreamFooterCellPresenter.swift
[Fixes #138356549](https://www.pivotaltracker.com/story/show/138356549)
> Select comment icon if content is present

- Sources/Controllers/Profile/Views/ProfileAvatarView.swift
- Sources/Utilities/InterfaceString.swift
Also changes copy used when uploading images.
[Fixes #140366453](https://www.pivotaltracker.com/story/show/140366453)
> Fix squashed avatar on profile

- Sources/Controllers/App/AppViewController.swift
[Fixes #138356797](https://www.pivotaltracker.com/story/show/138356797)
> Delay deeplinking on cold launch logged out

- Resources/emojis.json
- Specs/Networking/AutoCompleteServiceSpec.swift
[Finishes #140713825](https://www.pivotaltracker.com/story/show/140713825)
> Fix failing autocomplete spec, update emojis

- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/FollowingViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Networking/PostService.swift
Justin helped find these, so kudos
- Tracking for meta categories
- Correct tracking names
- Track comment views in post detail
- Track following
- Track grid/list toggle
[Finishes #140890503](https://www.pivotaltracker.com/story/show/140890503)
> Fixes to tracking

- Sources/Controllers/Login/LoginViewController.swift
- Sources/Model/Profile.swift
- Sources/Networking/ElloURI.swift
- Specs/Networking/ElloURISpec.swift
both quick fixes
[Finishes #141645723](https://www.pivotaltracker.com/story/show/141645723)
[Finishes #141634665](https://www.pivotaltracker.com/story/show/141634665)
> Adds announcement setting and fixes forgot password url

- Podfile
- Sources/Controllers/Stream/StreamKind.swift
- Sources/Model/User.swift
- Sources/Networking/ElloAPI.swift
- Specs/Controllers/Stream/StreamKindSpec.swift
- Specs/Helpers/Stubs.swift
- Specs/Model/UserSpec.swift
- Specs/Networking/ElloAPISpec.swift
[Finishes #141814473](https://www.pivotaltracker.com/story/show/141814473)
> Update trending to use the new endpoint

- Sources/Controllers/Profile/Calculators/ProfileNamesSizeCalculator.swift
- Sources/Controllers/Profile/Views/ProfileNamesView.swift
[Finishes #141745425](https://www.pivotaltracker.com/story/show/141745425)
> Truncate the name and username labels

- .travis.yml
- Ello.xcodeproj/project.pbxproj
- fastlane/Fastfile
Travis needs _some_ value for the new staging cocoapod keys, provide default values. Also includes fast lane rake task updates.
I'll be tweaking this PR until travis passes.
[Finishes #142779425](https://www.pivotaltracker.com/story/show/142779425)
> Update Fastlane and Travis config

- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Networking/ElloAPI.swift
- Sources/Utilities/Tracker.swift
- fetch 4 instead of 3 ([Finishes #142793195](https://www.pivotaltracker.com/story/show/142793195))
- tapping image should open post, not zoom image ([Finishes #141746013](https://www.pivotaltracker.com/story/show/141746013))
- track related post opens ([Finishes #142723269](https://www.pivotaltracker.com/story/show/142723269))
> Fixes to Related Posts

- Sources/AppDelegate.swift
[Fixes #141272111](https://www.pivotaltracker.com/story/show/141272111)
> Disable tracking in simulator

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/App/CredentialsScreen.swift
- Sources/Controllers/ForgotPassword/ForgotPasswordEmailScreen.swift
- Sources/Controllers/ForgotPassword/ForgotPasswordEmailViewController.swift
- Sources/Controllers/ForgotPassword/ForgotPasswordProtocols.swift
- Sources/Controllers/ForgotPassword/ForgotPasswordResetScreen.swift
- Sources/Controllers/ForgotPassword/ForgotPasswordResetViewController.swift
- Sources/Controllers/Join/JoinScreen.swift
- Sources/Controllers/Login/LoginScreen.swift
- Sources/Controllers/Login/LoginViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
- Sources/Networking/AuthState.swift
- Sources/Networking/ElloAPI.swift
- Sources/Networking/ElloAPIDescription.swift
- Sources/Networking/ElloURI.swift
- Sources/Networking/UserService.swift
- Sources/Utilities/InterfaceString.swift
- Sources/Utilities/Tracker.swift
- Specs/Networking/ElloURISpec.swift
- Specs/Utilities/ElloWebViewHelperSpec.swift
Blocked on API, so this is a WIP PR, but ready for review.
[Finishes #142779975](https://www.pivotaltracker.com/story/show/142779975)
> Native forgot password feature

- ShareExtension/ShareTrackerOverrides.swift
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/AutoComplete/AutoCompleteViewController.swift
- Sources/Controllers/Drawer/DrawerViewController.swift
- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Controllers/Stream/ContentFlagger.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
- Sources/Networking/ElloProvider.swift
- Sources/Utilities/Tracker.swift
[Finishes #143000501](https://www.pivotaltracker.com/story/show/143000501)
> Remove unnecessary/unused/maybe-private Crashlytics tracking

- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Views/CategoryCardListView.swift
- constraints were wacky
- tapping status bar to scroll to top didn't work on category screen
> Misc little fixes

- Sources/Controllers/Profile/Views/ProfileStatsView.swift
- Sources/Controllers/Stream/CellDequeing/ProfileStatsPresenter.swift
- Specs/Controllers/Stream/CellDequeing/ProfileStatsPresenterSpec.swift
[Finishes #141335381](https://www.pivotaltracker.com/story/show/141335381)
> Disable tap on following/followers if count == 0 or infinity

- Sources/Controllers/Drawer/DrawerViewController.swift
- Sources/Controllers/Drawer/DrawerViewDataSource.swift
- Sources/Utilities/Tracker.swift
[Finishes #142791681](https://www.pivotaltracker.com/story/show/142791681)
> Adds tracking to drawer taps

- ShareExtension/ShareTrackerOverrides.swift
- Sources/Controllers/Stream/Calculators/StreamImageCellSizeCalculator.swift
- Sources/Controllers/Stream/CellDequeing/CategoryCardCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/NotificationCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
- Sources/Controllers/Stream/CellDequeing/StreamTextCellPresenter.swift
- Sources/Controllers/Stream/Cells/CategoryCardCell.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.xib
- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Controllers/Stream/StreamCollectionViewLayout.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Extensions/ScreenExtensions.swift
- Sources/Utilities/Math.swift
This darn layout issue is tricky.
[Finishes #143618187](https://www.pivotaltracker.com/story/show/143618187)
> Doesn't exactly solve, but improves.

- Sources/Utilities/Tracker.swift
- event tracking
- identify
[Finishes #143837249](https://www.pivotaltracker.com/story/show/143837249)
> Adds 'ios' agent to tracking.

- Sources/Controllers/Stream/FollowingViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
[Finishes #141638127](https://www.pivotaltracker.com/story/show/141638127)
> Hides more-posts button when you pull-to-refresh, not scroll

- Resources/CustomSVGs/search_small_normal.svg
- Resources/CustomSVGs/search_small_selected.svg
- Sources/Controllers/Categories/CategoryScreen.swift
- Sources/Controllers/Search/SearchScreen.swift
- Sources/Utilities/InterfaceString.swift
- Sources/Views/SearchNavBarField.swift
- fix search prompt
- bump font to 14pt
- make magnifying glass slighly bigger
[Finishes #143992717](https://www.pivotaltracker.com/story/show/143992717)
[Finishes #141819823](https://www.pivotaltracker.com/story/show/141819823)
> Fix search screen issues

- Readme.md
- ShareExtension/Info.plist
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Specs/Controllers/Stream/PostbarControllerSpec.swift
- Support/Info.plist
Fixes double tap to love.
[Finishes #143970909](https://www.pivotaltracker.com/story/show/143970909)
> Release 2.2.1

- Resources/Settings.storyboard
- Resources/StubbedResponses/profile.json
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Model/Profile.swift
- Sources/Utilities/InterfaceString.swift
- Specs/Helpers/Stubs.swift
- Specs/Model/ProfileSpec.swift
Blocked on API (I assumed the property `is_community` will be added to `profile` objects).
[Finishes #143618527](https://www.pivotaltracker.com/story/show/143618527)
> Support 'isCommunity' profiles

- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/Tracker.swift
[Finishes #144123155](https://www.pivotaltracker.com/story/show/144123155)
> double tap love

- Ello.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- Rakefile
- Sources/AppDelegate.swift
- Sources/Ello-Bridging-Header.h
[Finishes #140890039](https://www.pivotaltracker.com/story/show/140890039)
> Adds new relic, assumes .env key 'NEW_RELIC_KEY'

- Sources/Controllers/BaseElloViewController.swift
- Sources/Controllers/Join/JoinScreen.swift
- Sources/Controllers/LoggedOut/LoggedOutViewController.swift
- Sources/Model/User.swift
- Sources/Utilities/Tracker.swift
- track login and join button taps
- track screen views (as events) when logged out
- add `is_featured` and `is_nabaroo` to identify properties
[Finishes #143615505](https://www.pivotaltracker.com/story/show/143615505)
[Finishes #144393253](https://www.pivotaltracker.com/story/show/144393253)
[Finishes #144370967](https://www.pivotaltracker.com/story/show/144370967)
[Finishes #144065163](https://www.pivotaltracker.com/story/show/144065163)
> Conversion and identify changes

- Ello.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- Sources/AppDelegate.swift
- Sources/Ello-Bridging-Header.h
[Finishes #144626521](https://www.pivotaltracker.com/story/show/144626521)
> Removes new relic 😞

- Sources/Controllers/Profile/ProfileGenerator.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
[Finishes #142710339](https://www.pivotaltracker.com/story/show/142710339)
> Fixes double post issue by assigning 'placeholderType'

- Sources/Networking/ElloAPI.swift
[Finishes #144959819](https://www.pivotaltracker.com/story/show/144959819)
> Remove 'seed' from discover params

- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Controllers/Stream/FollowingViewController.swift
- Sources/Networking/NewContentService.swift
- More Posts button should disappear after tapping the nav bar 'following' button
- More Posts button should not appear after creating a post
[Finishes #145358385](https://www.pivotaltracker.com/story/show/145358385)
> Fix 'More Posts' button

- Sources/Utilities/Tracker.swift
[Finishes #145311155](https://www.pivotaltracker.com/story/show/145311155)
> Add 'is_experimental' to Segment identify

- Sources/Utilities/Tracker.swift
[Finishes #145880049](https://www.pivotaltracker.com/story/show/145880049)
> Add 'hasAccount: true' to identify calls

- Sources/Controllers/Stream/CellDequeing/UserAvatarsCellPresenter.swift
- Sources/Controllers/Stream/Cells/UserAvatarsCell.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Model/UserAvatarCellModel.swift
[Finishes #145882805](https://www.pivotaltracker.com/story/show/145882805)
> Adds user avatar after loving or unloving a post

- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
If the current user is the only lover, show the drawer.  If no users love the post, hide the drawer.
[Finishes #145882805](https://www.pivotaltracker.com/story/show/145882805)
> Show and Hide the lovers drawer after love/unlove

- ShareExtension/Info.plist
- Sources/Controllers/Stream/CellDequeing/UserAvatarsCellPresenter.swift
- Sources/Controllers/Stream/Cells/UserAvatarsCell.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/UserAvatarCellModel.swift
- Sources/Utilities/Tracker.swift
- Support/Info.plist
- loving a post adds avatar to loves bar immediately (likewise for unloving)
- tracking `hasAccount: true` added to identify calls
> Release 2.5

- Ello.xcodeproj/project.pbxproj
- ShareExtension/Info.plist
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Support/Info.plist
Fixes crash on tapping search.
[Finishes #147259125](https://www.pivotaltracker.com/story/show/147259125)
> Release 2.5.1

- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Model/Post.swift
Keep 'loved' status up to date without reloading.
[Finishes #148373403](https://www.pivotaltracker.com/story/show/148373403)
> Fixes image refresh after loving a post or editorial.

- Sources/Model/Regions/Asset.swift
[Finishes #148787961](https://www.pivotaltracker.com/story/show/148787961)
> Fix editorial gifs

- ShareExtension/ShareViewController.swift
[Finishes #147866319](https://www.pivotaltracker.com/story/show/147866319)
> Fixes sharing many images by disabling 'Post' until images are processed

- Sources/Controllers/Stream/Cells/Editorials/EditorialPostStreamCell.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
[Finishes #148848711](https://www.pivotaltracker.com/story/show/148848711)
> Show editorials in 'landscape' if ipad is in landscape

- Sources/Controllers/Alerts/AlertAction.swift
- Sources/Controllers/Alerts/AlertViewController.swift
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/App/DebugController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteDetailController.swift
- Sources/Controllers/Home/HomeViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
- Sources/Networking/ElloURI.swift
- Sources/Utilities/DeepLinking.swift
- Sources/Utilities/Tracker.swift
[Finishes #149592221](https://www.pivotaltracker.com/story/show/149592221)
> Add Deep link support to artist invites

- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteBubbleCell.swift
- Sources/Controllers/ArtistInvites/ArtistInviteCellPresenter.swift
- Sources/Controllers/ArtistInvites/ArtistInviteControlsCell.swift
- Sources/Controllers/ArtistInvites/ArtistInviteDetailController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteDetailGenerator.swift
- Sources/Controllers/Home/HomeScreen.swift
- Sources/Controllers/Home/HomeViewController.swift
- Sources/Controllers/LoggedOut/LoggedOutViewController.swift
- Sources/Controllers/Stream/Calculators/ArtistInviteCellSizeCalculator.swift
- Sources/Controllers/Stream/FollowingViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/SimpleStreamViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Utilities/InterfaceString.swift
- Sources/Utilities/Tracker.swift
[Finishes #150023659](https://www.pivotaltracker.com/story/show/150023659)
> Logged out Artist Invites

- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/FreeMethods.swift
- Specs/Controllers/Stream/PostbarControllerSpec.swift
- Specs/Controllers/Stream/StreamDataSourceSpec.swift
- Specs/Utilities/FreeMethodsSpecs.swift
[Finishes #149199621](https://www.pivotaltracker.com/story/show/149199621)
> Batch updates to eliminate flickering

- Sources/Controllers/Stream/PostbarController.swift
[Finishes #150311790](https://www.pivotaltracker.com/story/show/150311790)
> Make love optimistic

- Sources/Controllers/Notifications/NotificationsGenerator.swift
- Sources/Model/ArtistInviteSubmission.swift
- Sources/Model/NotificationAttributedTitle.swift
- Sources/Networking/ArtistInviteService.swift
- Sources/Networking/ElloAPI.swift
- Sources/Networking/MappingType.swift
[Finishes #150347629](https://www.pivotaltracker.com/story/show/150347629)
> Adds artist invite submission accepted notifications

- Sources/Controllers/Stream/Cells/Editorials/EditorialPostCell.swift
[Finishes #150311790](https://www.pivotaltracker.com/story/show/150311790)
> Optimistic loves button states

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/App/DebugController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteAdminScreen.swift
- Sources/Controllers/ArtistInvites/ArtistInvitesScreen.swift
- Sources/Controllers/ArtistInvites/ArtistInvitesViewController.swift
- Sources/Controllers/Categories/CategoryScreen.swift
- Sources/Controllers/Categories/CategoryViewController.swift
- Sources/Controllers/Editorials/EditorialsScreen.swift
- Sources/Controllers/Home/HomeScreen.swift
- Sources/Controllers/Home/HomeViewController.swift
- Sources/Controllers/Notifications/NotificationsGenerator.swift
- Sources/Model/ArtistInviteSubmission.swift
- Sources/Networking/ElloProvider.swift
- Sources/Networking/ElloProviderLinkExension.swift
- Sources/Networking/ResponseConfig.swift
- Sources/Views/Screens/HomeSubviewScreen.swift
[Finishes #150023659](https://www.pivotaltracker.com/story/show/150023659)
> Misc fixes

- NotificationServiceExtension/Info.plist
- README.md
- ShareExtension/Info.plist
- ShareExtension/ShareViewController.swift
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/Editorials/EditorialsGenerator.swift
- Sources/Controllers/Notifications/NotificationCell.swift
- Sources/Controllers/Notifications/NotificationsGenerator.swift
- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Controllers/Stream/CellDequeing/NotificationCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamTextCell.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
- Sources/Model/JWT.swift
- Sources/Networking/ElloProvider.swift
- Sources/Networking/ElloURI.swift
- Sources/ThirdParty/PromiseKitExtensions.swift
- Specs/Controllers/Stream/StreamDataSourceSpec.swift
- Support/Info.plist
makes them tappable
[Finishes #150347629](https://www.pivotaltracker.com/story/show/150347629)
> Fixes artist invite submission notifications

- Ello.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- ShareExtension/ExtensionOverrides.swift
- ShareExtension/ShareViewController.swift
- Sources/Controllers/App/DebugTrackingController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteBubbleCell.swift
- Sources/Controllers/ArtistInvites/ArtistInviteHeaderCell.swift
- Sources/Controllers/Notifications/AnnouncementCell.swift
- Sources/Controllers/Omnibar/OmnibarImageCell.swift
- Sources/Controllers/Omnibar/OmnibarScreenTableViewDelegate.swift
- Sources/Controllers/Onboarding/OnboardingProfileScreen.swift
- Sources/Controllers/Profile/ProfileScreen.swift
- Sources/Controllers/Profile/Views/ProfileAvatarView.swift
- Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
- Sources/Controllers/Stream/Cells/EditorialCell.swift
- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Controllers/Stream/ContentFlagger.swift
- Sources/Ello-Bridging-Header.h
- Sources/Extensions/UIImagePickerController.swift
- Sources/Model/ElloLinkedStore.swift
- Sources/Model/JSONAble.swift
- Sources/Model/UserFlag.swift
- Sources/Networking/CategoryService.swift
- Sources/Networking/PagePromotionalService.swift
- Sources/Utilities/Tracker.swift
- Specs/Controllers/Stream/ContentFlaggerSpec.swift
- Specs/Utilities/Specs-Bridging-Header.h
[Finishes #150023659](https://www.pivotaltracker.com/story/show/150023659)
[Finishes #150490094](https://www.pivotaltracker.com/story/show/150490094)
> Fixes tracking in extensions and artist invite submissions

- Sources/Controllers/App/AppViewController.swift
- Sources/Model/ElloLinkedStore.swift
[Finishes #150023659](https://www.pivotaltracker.com/story/show/150023659)
> Fixes Artist Invite Submissions

- Sources/Controllers/Stream/Cells/EditorialCell.swift
- Sources/Controllers/Stream/Cells/Editorials/EditorialExternalCell.swift
- Sources/Controllers/Stream/Cells/Editorials/EditorialInternalCell.swift
- Sources/Controllers/Stream/Cells/Editorials/EditorialPostCell.swift
- Sources/Controllers/Stream/Cells/Editorials/EditorialTitledCell.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/Cells/StreamTextCellHTML.swift
- Sources/Model/Editorial.swift
[Finishes #149899123](https://www.pivotaltracker.com/story/show/149899123)
> Support Editorial HTML

- Sources/Controllers/Alerts/AlertViewController.swift
[Finishes #150614736](https://www.pivotaltracker.com/story/show/150614736)
> fix alert controller sizing

- Sources/Controllers/ArtistInvites/ArtistInviteControlsCell.swift
- Sources/Controllers/Stream/Calculators/ArtistInviteCellSizeCalculator.swift
[Finishes #150858997](https://www.pivotaltracker.com/story/show/150858997)
> Only show submit button if artist invite is open

- Sources/Controllers/AutoComplete/AutoComplete.swift
- Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
- Specs/Controllers/AutoComplete/AutoCompleteSpec.swift
The logic for detecting string position is hard, but now it's fixed.
[Finishes #150689104](https://www.pivotaltracker.com/story/show/150689104)
> Fixes autocomplete

- Sources/Controllers/Stream/CellDequeing/StreamHeaderCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/User.swift
- Specs/Model/UserSpec.swift
As long as the API supports it.
[Finishes #150688904](https://www.pivotaltracker.com/story/show/150688904)
> Staff can delete any comment

- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeViewController.swift
- Sources/Controllers/Onboarding/OnboardingInterestsViewController.swift
- Sources/Controllers/Onboarding/OnboardingViewController.swift
- Sources/Utilities/Onboarding.swift
- Specs/Utilities/OnboardingSpec.swift
If `onboardingVersion < 3`, we show the Creator Type onboarding step.
Needs a DB update before it can be released.
CC @Justin-Holmes
[Finishes #150689284](https://www.pivotaltracker.com/story/show/150689284)
> Adds Creator Type onboarding

- Sources/Controllers/Stream/Cells/StreamCellType.swift
[Finishes #151195665](https://www.pivotaltracker.com/story/show/151195665)
> Fixed: Editorial tapping opens two posts

- Sources/Utilities/Onboarding.swift
Don't go through entire onboarding if any version of onboarding is set
[Finishes #151226553](https://www.pivotaltracker.com/story/show/151226553)
> Fix onboarding logic

- Sources/AppDelegate.swift
- Sources/Controllers/BaseElloViewController.swift
- Sources/Controllers/ElloTabBarController.swift
- Sources/Controllers/LoggedOut/LoggedOutViewController.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeViewController.swift
- Sources/Controllers/PushNotifications/PushNotificationController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
[Finishes #151337761](https://www.pivotaltracker.com/story/show/151337761)
> Fixes I found on 2.11

- Sources/Controllers/Onboarding/OnboardingCreatorTypeScreen.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeViewController.swift
- Sources/Utilities/InterfaceString.swift
[Finishes #150689284](https://www.pivotaltracker.com/story/show/150689284)
> Add header to creator type onboarding

- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/StreamDataSource.swift
[Finishes #151494415](https://www.pivotaltracker.com/story/show/151494415)
> Don't refresh all user cells when updating relationship

- Sources/Controllers/Onboarding/OnboardingCreatorTypeProtocols.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeScreen.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeViewController.swift
- Sources/Controllers/Settings/DynamicSettingsViewController.swift
Fixes the margins, too, so the text is closer to the top when the label is hidden.
> Fixes the showing/hiding of the intro text in creator type onboarding

- Sources/Controllers/ArtistInvites/ArtistInvitesViewController.swift
- Sources/Controllers/Home/HomeScreen.swift
- Sources/Controllers/Notifications/NotificationCell.swift
- Sources/Controllers/Stream/Cells/Editorials/EditorialTitledCell.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Views/ElloNavigationBar.swift
- Sources/Views/ElloWebView.swift
- Fixes navigation bar title (prevent overlap)
- Adds a minimum top inset when browsing artist invites
- remove a black line at the buttom of some web views
> Misc visual fixes

- Sources/Controllers/ArtistInvites/ArtistInviteBubbleCell.swift
- Sources/Controllers/ArtistInvites/ArtistInviteHeaderCell.swift
- Sources/Controllers/Stream/Calculators/ArtistInviteCellSizeCalculator.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Views/StyledLabel.swift
Title and Invite Type now have multiline support.
[Finishes #151694546](https://www.pivotaltracker.com/story/show/151694546)
> Assign dynamic heights to Artist Invites

- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Specs/Controllers/Categories/CategoryViewControllerSpec.swift
- Specs/Controllers/Omnibar/OmnibarScreenSpec.swift
Wasn't supporting the new ElloNavigationBar
[Finishes #151735206](https://www.pivotaltracker.com/story/show/151735206)
> Set the title correctly on Omnibar navigation bar

- Resources/Settings.storyboard
> I'm getting more and more convinced that Storyboards are a reasonable idea
> — no one reasonable
> Remove height constraint from Settings storyboard

- Ello.xcodeproj/project.pbxproj
- NotificationServiceExtension/NotificationService.swift
- Sources/Controllers/App/DebugController.swift
- Sources/Controllers/App/DebugServer.swift
- Sources/Utilities/FreeMethods.swift
The issue with notifications was that the assets hadn't been processed, this is why things worked great when I tested against an existing post, but broke down on *actual* new posts.
[Finishes #149576537](https://www.pivotaltracker.com/story/show/149576537)
> Fixes notifications on brand new posts

- NotificationServiceExtension/Info.plist
- ShareExtension/Info.plist
- Support/Info.plist
[Finishes #151921947](https://www.pivotaltracker.com/story/show/151921947)
> Release 2.12

- NotificationServiceExtension/NotificationService.swift
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/PushNotifications/PushNotificationController.swift
- Sources/Controllers/Stream/StreamResponders.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
- Sources/Networking/ElloURI.swift
- Sources/Utilities/ElloWebViewHelper.swift
[Finishes #151893746](https://www.pivotaltracker.com/story/show/151893746)
> Refactor ElloURI

- Sources/Controllers/ArtistInvites/ArtistInviteAdminController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteAdminControlsCell.swift
- Sources/Controllers/ArtistInvites/ArtistInviteAdminScreen.swift
- Sources/Controllers/ArtistInvites/ArtistInviteDetailGenerator.swift
- Sources/Controllers/ArtistInvites/ArtistInvitesProtocols.swift
- Sources/Model/ArtistInvite.swift
- Sources/Model/ArtistInviteSubmission.swift
- Sources/Utilities/InterfaceString.swift
[Finishes #151880759](https://www.pivotaltracker.com/story/show/151880759)
> Adds 'declined' action and tab to artist invites

- Sources/Controllers/App/DebugTrackingController.swift
- Sources/Controllers/Categories/CategoryScreen.swift
- Sources/Controllers/Onboarding/OnboardingCreatorTypeScreen.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/FreeMethods.swift
> Refactor animations

- Sources/Model/Activity.swift
- Sources/Model/Category.swift
- Sources/Model/Comment.swift
- Sources/Model/JSONAble.swift
- Sources/Model/Love.swift
- Sources/Model/Notification.swift
- Sources/Model/PagePromotional.swift
- Sources/Model/Post.swift
- Sources/Model/Profile.swift
- Sources/Model/Promotional.swift
- Sources/Model/Regions/Asset.swift
- Sources/Model/Regions/Attachment.swift
- Sources/Model/Regions/EmbedRegion.swift
- Sources/Model/Regions/ImageRegion.swift
- Sources/Model/Relationship.swift
- Sources/Model/User.swift
- Sources/Model/Watch.swift
- Specs/Helpers/Stubs.swift
- Specs/Model/ActivitySpec.swift
- Specs/Model/CommentSpec.swift
- Specs/Model/LoveSpec.swift
- Specs/Model/PostSpec.swift
- Specs/Model/UserSpec.swift
- Specs/Model/WatchSpec.swift
Swift 4 requires a lot more `@objc` to tell the compiler to expose a func/var to the objc runtime.
> Fix Settings

- Sources/Controllers/Stream/StreamViewController.swift
The cells were being set, but the layout wasn't being updated.
> Fix cell toggling

- Sources/Controllers/Notifications/NotificationsScreen.swift
Swift 4 method visibility *again*.
> Fixes to notification filters

- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.xib
- Sources/Controllers/Stream/StreamResponders.swift
- Sources/Controllers/Stream/StreamViewController.swift
> Fixes tapping on artist invite submission header

- Resources/Settings.storyboard
- Sources/Controllers/Onboarding/OnboardingProfileScreen.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Settings/SettingsViewController.swift
- Sources/Networking/ImageRegionData.swift
- Sources/Networking/ProfileService.swift
and update profile screen for current user
> Support animated gif in settings

- Sources/Controllers/ArtistInvites/ArtistInviteDetailGenerator.swift
- Sources/Controllers/Stream/StreamCellItemParser.swift
- Sources/Controllers/Stream/StreamGenerator.swift
- Sources/Controllers/Stream/StreamKind.swift
- Sources/Networking/ElloProviderErrors.swift
- Sources/Networking/StreamService.swift
[Finishes #152730434](https://www.pivotaltracker.com/story/show/152730434)
> Fixes infinite scrolling in artist invite submissions

- Sources/Controllers/Categories/CategoryViewController.swift
move secondary/tertiary to All only
[Finishes #152723817](https://www.pivotaltracker.com/story/show/152723817)
> Only show primary categories in Discover

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
- Sources/Controllers/Omnibar/OmnibarScreenTextViewDelegate.swift
> Fixes the omnibar!

- Sources/Controllers/ArtistInvites/ArtistInviteDetailController.swift
- Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
- Sources/Controllers/Stream/Detail/PostDetailViewController.swift
- Sources/Model/ArtistInvite.swift
- Sources/Model/Post.swift
- Sources/Utilities/Tracker.swift
[Finishes #152490791](https://www.pivotaltracker.com/story/show/152490791)
> Add Share button to Post Detail and Artist Invites

- Sources/Controllers/BaseElloViewController.swift
- Sources/Controllers/Omnibar/OmnibarScreenTextViewDelegate.swift
- Sources/Controllers/Stream/StreamableViewController.swift
[Finishes #153182216](https://www.pivotaltracker.com/story/show/153182216)
> Adds tap-to-show areas when nav & tab bars are hidden

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Stream/CellDequeing/LoadingCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamCellType.swift
- Sources/Controllers/Stream/Cells/StreamLoadingCell.swift
- Sources/Controllers/Stream/Cells/StreamPageLoadingCell.swift
- Sources/Controllers/Stream/StreamCellItem.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Utilities/ElloScrollLogic.swift
- Sources/Views/LoadingGradientLayer.swift
- Sources/Views/StartupGradientLayer.swift
[Finishes #153260194](https://www.pivotaltracker.com/story/show/153260194)
> Adds gradient animation

- Ello.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- Sources/Controllers/Alerts/AlertPresentationController.swift
- Sources/Controllers/Alerts/AlertViewController.swift
- Sources/Controllers/ArtistInvites/ArtistInviteDetailController.swift
- Sources/Controllers/Lightbox/LightboxProtocols.swift
- Sources/Controllers/Lightbox/LightboxScreen.swift
- Sources/Controllers/Lightbox/LightboxViewController.swift
- Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Controllers/Stream/ElloDataSource.swift
- Sources/Controllers/Stream/StreamImageViewer.swift
- Sources/Controllers/Stream/StreamResponders.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Model/Regions/ImageRegion.swift
- Specs/Controllers/Stream/CellDequeing/StreamImageCellPresenterSpec.swift
- Specs/Controllers/Stream/StreamImageViewerSpec.swift
[Finishes #153265791](https://www.pivotaltracker.com/story/show/153265791)
> Adds iOS Lightbox

- Sources/Controllers/Stream/Cells/StreamImageCell.swift
- Sources/Controllers/Stream/StreamViewController.swift
- Sources/Utilities/InterfaceString.swift
[Finishes #153383885](https://www.pivotaltracker.com/story/show/153383885)
> Add copy/save to images on long press

- Sources/Controllers/Alerts/AlertCell.swift
- Sources/Controllers/Omnibar/OmnibarScreen.swift
- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Utilities/InterfaceString.swift
Includes link editing bug fix, rotation fix, and adds a "Uploading post" message.
[Finishes #153731763](https://www.pivotaltracker.com/story/show/153731763)
> Fixes to posting

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Profile/ProfileProtocols.swift
- Sources/Controllers/Profile/ProfileScreen.swift
- Sources/Controllers/Profile/ProfileViewController.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Views/AvatarButton.swift
- Sources/Views/ElloNavigationBar.swift
- Sources/Views/PersistentBackButton.swift
[Finishes #153835461](https://www.pivotaltracker.com/story/show/153835461)
> Adds a persistent back button

- Sources/Controllers/Notifications/NotificationCell.swift
- Sources/Controllers/Notifications/NotificationsViewController.swift
- Sources/Model/Activity.swift
- Sources/Model/NotificationAttributedTitle.swift
- Sources/Model/Profile.swift
- Sources/Views/ElloTextView.swift
- Sources/Views/PersistentBackButton.swift
[Finishes #153605056](https://www.pivotaltracker.com/story/show/153605056)
> Adds setting and in-app notification for "a follower's post was accepted"

- Sources/Controllers/Profile/ProfileScreen.swift
- Sources/Controllers/Search/SearchScreen.swift
- Sources/Controllers/Stream/StreamableViewController.swift
- Sources/Views/ElloNavigationBar.swift
- Sources/Views/PersistentBackButton.swift
[Finishes #153835461](https://www.pivotaltracker.com/story/show/153835461)
> Adds persisent back button to search and profile, and visual fixes

- Sources/Controllers/Lightbox/LightboxScreen.swift
- mainly zooming and panning
- also the loader was screwy
> Fixes to lightbox

- NotificationServiceExtension/Info.plist
- ShareExtension/Info.plist
- Sources/Model/Profile.swift
- Support/Info.plist
Quick fix to Settings so that `isCollaborateable` and `isHireable` are saved.
Also adds `notifyOfApprovedSubmissionsFromFollowingViaEmail` setting.
> Release 2.16.1

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Omnibar/OmnibarViewController.swift
- Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
- Sources/Controllers/Stream/StreamCellItemParser.swift
- Sources/Extensions/NumberExtensions.swift
- Sources/Model/Activity.swift
- Sources/Model/ArtistInviteSubmission.swift
- Sources/Model/Comment.swift
- Sources/Model/Editorial.swift
- Sources/Model/Love.swift
- Sources/Model/Model.swift
- Sources/Model/Notification.swift
- Sources/Model/NotificationFilterType.swift
- Sources/Model/Post.swift
- Sources/Model/Profile.swift
- Sources/Model/Regions/RegionParser.swift
- Sources/Model/Relationship.swift
- Sources/Model/Watch.swift
- Sources/Networking/Parsers/CommentParser.swift
- Sources/Networking/Parsers/PostParser.swift
- Sources/Networking/Parsers/UserParser.swift
- Sources/Networking/PostEditingService.swift
- Sources/Utilities/Preloader.swift
- Specs/Helpers/Stubs.swift
And make post/comment content not optional
> Refactor links into a fancy enum

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/Badges/BadgesViewController.swift
- Sources/Controllers/Stream/CollectionViewDataSource.swift
- Sources/Controllers/Stream/PostbarController.swift
- Sources/Controllers/Stream/StreamCellItem.swift
- Sources/Controllers/Stream/StreamCellItemParser.swift
- Sources/Controllers/Stream/StreamDataSource.swift
- Sources/Model/Announcement.swift
- Sources/Model/ArtistInvite.swift
- Sources/Model/ArtistInviteSubmission.swift
- Sources/Model/Category.swift
- Sources/Model/CategoryPost.swift
- Sources/Model/Comment.swift
- Sources/Model/Editorial.swift
- Sources/Model/LocalPerson.swift
- Sources/Model/Love.swift
- Sources/Model/Notification.swift
- Sources/Model/Post.swift
- Sources/Model/Protocols/Groupable.swift
- Sources/Model/Regions/Attachment.swift
- Sources/Model/Relationship.swift
- Sources/Model/Watch.swift
- Sources/Networking/RelationshipService.swift
- Specs/Controllers/Omnibar/OmnibarViewControllerSpec.swift
- Specs/Controllers/Stream/Cells/AnnouncementCellSpec.swift
- Specs/Controllers/Stream/CollectionViewDataSourceSpec.swift
- Specs/Controllers/Stream/StreamDataSourceSpec.swift
- Specs/Helpers/Stubs.swift
- Specs/Model/NotificationSpec.swift
> Refactor groupId

- Ello.xcodeproj/project.pbxproj
- Sources/Controllers/App/AppViewController.swift
- Sources/Controllers/Loves/LovesViewController.swift
- Sources/Controllers/Profile/ProfileViewController.swift
Uses GraphQL - this was already done, apparently, so the code just needed a clean up.
> LovesViewController

- Resources/SVGs/bolt_selected.svg
- Sources/Controllers/Stream/StreamDataSource.swift
due to new profile header cells
> Fixes repost insertion
