Sources/Model/User.swift
Specs/Controllers/Stream/CellDequeing/StreamHeaderCellPresenterSpec.swift

enables deleting a comment on a repost of your post

Check parentPost.author *and* repostAuthor when check authorship

---

.travis.yml
Podfile
Podfile.lock

Reduces Swift 2.2 warnings, and keeps us fresh and clean.

Updates Moya to 6.5, and Result to 2.0

---

Sources/Model/ExperienceUpdate.swift
Specs/Model/ExperienceUpdateSpec.swift

Otherwise the "still in memory" post will have its comment count updated twice

Store the updated post AFTER posting the notification

---

Sources/Controllers/Stream/CellDequeing/StreamFooterCellPresenter.swift
Sources/Extensions/NumberExtensions.swift
Specs/Controllers/Stream/CellDequeing/StreamFooterCellPresenterSpec.swift
Specs/Extensions/NumberExtensionsSpec.swift

In grid view, the following changes:
- iphone5 / 4" is too small for any more numbers, so no change
- iphone6 / iphone6+ is large enough for more numbers, but large numbers are more truncated

Set the views/reposts/loves count appropriately

---

Sources/Controllers/Stream/Cells/StreamEmbedCell.xib

This fixes a regression introduced when we added double tap to love. We removed the IBAction in `StreamImageCell` but forgot to remove it in the subclass `StreamEmbedCell` nib.
[fixes #122085233](https://www.pivotaltracker.com/story/show/122085233)

Remove nib IBAction tap in embed cells

---

Sources/Controllers/Stream/Cells/StreamImageCell.swift

Youtube embedded links did not allow interaction with the play button when thumbnail failed to load.
Partially [fixes #121961001](https://www.pivotaltracker.com/story/show/121961001)
The remaining fix is determining why the thumbnail was not included in the json.
```
{
"kind": "embed",
"data": {
"service": "youtube",
"id": "T0GQIq64cCk",
"url": "https://www.youtube.com/watch?v=T0GQIq64cCk",
"thumbnail_large_url": null,
"thumbnail_small_url": null
}
}
```

Don't disable embed cell interactions

---

Sources/Networking/PostService.swift
Sources/Networking/StreamService.swift
Sources/Utilities/Preloader.swift
Specs/Utilities/PreloaderSpec.swift

`Preloader().preloadImages(...)` never used the `streamKind` parameter. Less code is the best code!

Remove streamkind from preloadImage calls

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Discover/DiscoverMoreCategoriesViewController.swift
Sources/Controllers/Notifications/NotificationsFilterBar.swift
Sources/Model/CategoryLevel.swift
Sources/Model/CategoryList.swift
Sources/Views/BlackBar.swift
Sources/Views/ElloNavigationBar.swift
Sources/Views/Screens/ElloScreen.swift

Visual fixes, category fixes

---

ShareExtension/ShareTrackerOverrides.swift
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/Profile/ProfileHeaderCellSizeCalculator.swift
Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
Sources/Controllers/Stream/Cells/StreamImageCell.swift
Sources/Controllers/Stream/Cells/StreamImageCellSizeCalculator.swift
Sources/Controllers/Stream/Cells/StreamNotificationCellSizeCalculator.swift
Sources/Controllers/Stream/Cells/StreamTextCellSizeCalculator.swift
Sources/Controllers/Stream/StreamCollectionViewLayout.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamImageViewer.swift
Sources/Controllers/Stream/StreamKind.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Extensions/ScreenExtensions.swift
Sources/Model/Regions/Asset.swift
Sources/Utilities/Application.swift
Sources/Utilities/Math.swift
Specs/Controllers/Stream/StreamNotificationCellSizeCalculatorSpec.swift
Specs/Environment/AppSetupSpec.swift
Specs/Fakes/FakeProfileHeaderCellSizeCalculator.swift
Specs/Fakes/FakeStreamNotificationCellSizeCalculator.swift
Specs/Fakes/FakeStreamTextCellSizeCalculator.swift

Images were being stretched because the `cell.frame` can change *after* `cellForItemAtIndexPath` is called.
The frame is used to determine the "expected height", and so this check needs to be in `layoutSubviews`, where it can listen for all changes to the frame.
Originally I created this branch to support 3-columns on all streams - that's done, too!

Re-fixes column layouts (image stretching) and adds support for 3 columns on all streams

---

Sources/Controllers/SignIn/SignInViewController.swift
Sources/Controllers/SignIn/SignInViewController.xib
Sources/Utilities/InterfaceString.swift
Sources/Utilities/Validator.swift
Specs/Controllers/SignIn/SignInViewControllerSpec.swift
Specs/Utilities/ValidatorSpec.swift

Adds username validation, and validates email *or* username before sending credentials

Accept username *or* email in Sign In screen

---

Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/SimpleStreamViewController.swift
Sources/Model/Tracker.swift

1. Remove duplicate "Profile/Post viewed" events (the `screenAppeared` tracking takes care of these)
2. Override the `tracking` in `SimpleStreamViewController`
These should make life easier for @Justin-Holmes

Changes screen tracking

---

Sources/Controllers/Intro/IntroViewController.swift

Noticed a UI bug in on boarding, current if you let go of the page before it finishes animating, the pageControl doesn't update.
I've found that using `didFinishAnimating` has fixed that in the past.
This hasn't been tested.

use didFinishAnimating to get new current page for onboarding pageVC

---

Sources/Controllers/Omnibar/OmnibarScreen.swift
Sources/Utilities/Keyboard.swift
Sources/controllers/Alerts/AlertViewControllerKeyboardExtension.swift
Specs/Controllers/SignIn/SignInViewControllerSpec.swift
Specs/Utilities/KeyboardSpec.swift

this made sense to me - it hasn't been tested. 
I thought a global `private let` didn't seem as clean as a `public static let`

Keyboard.shared() -> Keyboard.shared

---

Sources/Controllers/Stream/CellDequeing/StreamHeaderCellPresenter.swift
Sources/Controllers/Stream/StreamKind.swift
Specs/Controllers/Stream/CellDequeing/StreamHeaderCellPresenterSpec.swift
Specs/Controllers/Stream/StreamKindSpec.swift

Last PR for 1.9.1 - hide category everywhere *except* the `discover/featured/` stream

Only show category in .Discover(.Featured) stream

---

Ello.xcodeproj/project.pbxproj
Sources/AppDelegate.swift
Sources/Controllers/App/AppViewController.swift
Sources/Model/ElloLinkedStore.swift
Sources/Model/User.swift
Sources/Networking/ElloManager.swift
Sources/Utilities/Defaults.swift
Sources/Utilities/ObjectCache.swift
Sources/Utilities/Onboarding.swift
Specs/Helpers/Stubs.swift
Specs/Utilities/ObjectCacheSpec.swift
Specs/Utilities/OnboardingSpec.swift

See specs for a complete table of expectations, but essentially:
- only show onboarding once, on any platform
- if web value is nil, assume it's been seen
- if web and local are both < current, show onboarding
then:
- update the API as needed

Update the onboarding logic

---

Resources/StubbedResponses/CustomResponses/affiliate-image-region.json
Resources/StubbedResponses/activity-own-post.json
Resources/StubbedResponses/asset.json
Resources/StubbedResponses/friends.json
Resources/StubbedResponses/image-region.json
Resources/StubbedResponses/posts.json
Sources/Model/Regions/Asset.swift
Sources/Model/User.swift
Specs/Helpers/Stubs.swift
Specs/Model/CommentSpec.swift
Specs/Model/PostSpec.swift
Specs/Model/Regions/AssetSpec.swift
Specs/Model/Regions/ImageRegionSpec.swift
Specs/Model/UserSpec.swift
Specs/Networking/ProfileServiceSpec.swift

uses `original` instead of `hdpi`, and uses `xhdpi` instead of `hdpi` on iPhone, which should look much better on iPhone 6+
The `hdpi` cover image is actually pretty dang small.  This brings us closer in line w/ webapp (esp in landscape).
Also, this PR removes all references to `xxhdpi` and `xxxhdpi`, because the server doesn't generate those, and we'll never get them.

Fixes the cover image on iPad

---

Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift

This covers itunes store links (and any other app urls)

Close the browser (and open externally) on failed URLs

---

Sources/Controllers/Profile/ProfileGenerator.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/StreamGenerator.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Networking/AsyncOperation.swift
Sources/Networking/ElloAPI.swift
Sources/Utilities/FreeMethods.swift
Specs/Controllers/Profile/ProfileGeneratorSpec.swift
Specs/Controllers/Stream/Detail/PostDetailGeneratorSpec.swift
Specs/Networking/AsyncOperationSpec.swift

Fixes pagination, user loading, performance

---

Ello.xcodeproj/project.pbxproj

Since we use `release` branches, the calculation of number of commits is not always based on `master`.  This, instead, looks at the current branch (aka `HEAD`).

Calculate number of commits based on HEAD, not master

---

Sources/Controllers/Stream/Cells/StreamImageCell.swift
Sources/Model/Tracker.swift

Use "Buy Button Link Visited" event, as it is in segment.

Consistent naming for 'buy button link'

---

Sources/Controllers/Notifications/NotificationCell.swift
Sources/Controllers/Stream/CellDequeing/NotificationCellPresenter.swift
Sources/Controllers/Stream/Cells/StreamNotificationCellSizeCalculator.swift
Sources/Model/JSONAble.swift
Specs/Controllers/Stream/StreamNotificationCellSizeCalculatorSpec.swift

and only fire `onHeightMismatch` after everything (image & message HTMl) have loaded.  The `height` passed in is from `layoutSubviews`, so is guaranteed to be correct.

Fix `NotificationCell` sizing and calculator code

---

Sources/Controllers/Stream/StreamViewController.swift

Easy fix - the refactor to using `guard` resulted in a flipped conditional.

Re-enables "tap text to open" in grid view

---

Sources/Controllers/Profile/ProfileGenerator.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/StreamGenerator.swift
Sources/Networking/ElloProvider.swift
Sources/Networking/StreamService.swift
Specs/Controllers/Profile/ProfileGeneratorSpec.swift
Specs/Controllers/Stream/Detail/PostDetailGeneratorSpec.swift
Specs/Helpers/ElloSpecHelper.swift
Specs/Model/PostSpec.swift

The cast to `[Post]` was failing because "no content" is returned as `data: ""`.  This checks for `""` and the service replies with an empty posts array in that case.  The ProfileGenerator then calls `secondaryJSONAbleNotFound` on the destination, which shows the "This person hasn't posted yet" UI.

Fixes the "error" when showing a user with no posts

---

Sources/Controllers/Profile/ProfileGenerator.swift
Sources/Networking/ElloAPI.swift

- `/users/id` returns posts, and the number is determined by `post_count`
- `/users/id/posts` returns posts, and the number is determined by `per_page`
😐

Fixes the per-page param name

---

Ello.xcodeproj/project.pbxproj
Ello.xcodeproj/xcshareddata/xcschemes/ElloDev.xcscheme
Sources/Controllers/Alerts/AlertViewController.swift
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/AutoComplete/AutoCompleteViewController.swift
Sources/Utilities/FreeMethods.swift
Support/ElloDev.entitlements

There is a new "ElloDev" scheme, which is configured to use the "Debug" setting on all builds - specifically Run and Archive.
Meanwhile, "Ello" scheme is the opposite - it uses the "Release" build config for Run and Archive.
The entitlements, bundle ID, and icon are all tied to the build config, so just using the correct Scheme will configure each app.
The only manual step is pointing to prod vs staging.

Changes build settings to support "ElloDev" and "Ello" apps

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/App/DebugTodoController.swift
Sources/Controllers/Join/JoinScreen.swift
Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Onboarding/OnboardingProtocols.swift
Sources/Controllers/Onboarding/OnboardingScreen.swift
Sources/Utilities/Onboarding.swift
Sources/Views/StyledButton.swift
Specs/Utilities/OnboardingSpec.swift

- disables the 'Pick 3/2/1' and 'Invite People' buttons until they're green
- makes text fields easier to tap in Sign Up
- changes onboarding logic: show if version is `nil`, otherwise ignore.
- changes onboarding saving logic: updates version after setting the categories (even if you force quit the app)

Changes to Onboarding

---

Sources/Controllers/Onboarding/OnboardingScreen.swift
Sources/Controllers/Settings/DeleteAccountConfirmationView.xib

The `promptButton` defaults to disabled, but I neglected to *re-enable* it during the last step.
@steam I could go either way on the placement of `enabled=false`.  Looking at it a second time, are you still leaning towards putting it in `style()`?

Fixes onboarding so user can finish last step

---

Resources/Settings.storyboard
Sources/Controllers/Join/JoinProtocols.swift
Sources/Controllers/Join/JoinScreen.swift
Sources/Controllers/Join/JoinViewController.swift
Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Onboarding/CreateProfileProtocols.swift
Sources/Controllers/Onboarding/CreateProfileScreen.swift
Sources/Controllers/Onboarding/CreateProfileViewController.swift
Sources/Controllers/Onboarding/InviteFriendsViewController.swift
Sources/Controllers/Onboarding/OnboardingProtocols.swift
Sources/Controllers/Onboarding/OnboardingViewController.swift
Specs/Controllers/Join/JoinViewControllerSpec.swift

Solves remaining QA issues:
Also I added an `OnboardingProceed` enum, which is passed into the `proceed()` closure to make it clear what should happen next (`.Continue`, `.Abort`, `.Error`).  These used to be `true / false / nil`, which are not very clear.

Validation fixes during onboarding

---

Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/PushNotifications/PushNotificationController.swift
Support/ElloDev.entitlements

iOS 10 introduced new api for subscribing to and handling push notifications. See https://developer.apple.com/reference/usernotifications.
This caused devices running iOS 10 to be unable to route Ello push notifications to the correct screen in app. The app now handles both iOS 10 and pre iOS 10 push notifications correctly.
*Note - needs to be tested on an iOS 9 device.

Fix iOS 10 push notification routing

---

Sources/Controllers/Stream/CellDequeing/CategoryCardCellPresenter.swift
Sources/Controllers/Stream/Cells/CategoryCardCell.swift

So that 'selected' is only used on `.SelectableCategoryCard` types

Fixes to the `CategoryCardCell`

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Stream/Cells/CategoryCardCell.swift

Apparently this isn't allowed:
```swift
override public var selectable: Bool {
didSet { self.selected = selected }
}
```
This code is better anyway, it's clearer, I think.

Fixes category card fixes

---

Ello.xcodeproj/project.pbxproj
Resources/Main.storyboard
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Views/ElloCollectionView.swift

The generators, [ProfileGenerator](https://github.com/ello/ello-ios/blob/master/Sources/Controllers/Profile/ProfileGenerator.swift) and [PostDetailGenerator](https://github.com/ello/ello-ios/blob/master/Sources/Controllers/Stream/Detail/PostDetailGenerator.swift) are great... except when they are not. They speed up concurrent network request loading but have inadvertently affected other UI updates that occur in app. [StreamDataSource](https://github.com/ello/ello-ios/blob/master/Sources/Controllers/Stream/StreamDataSource.swift) is responsible for updating cells by reloading them when user interactions occur. We believe that loading of data, updating collection views and updates based on user interaction results in our data sources and collection views getting out of sync. 
This PR is the …

WIP: Serialize collection view cell reloads

---

Sources/Views/ElloCollectionView.swift
Specs/Controllers/Stream/StreamDataSourceSpec.swift

This is a bummer but AsyncOperation does not play nice with specs. Just bail on the foreground performBatchUpdates in specs.

Bail on ElloCollectionView.reload in specs

---

.travis.yml

Part of a recent fire drill Apple ran was an AppStore submission rejection due to non-Apple accessing code using names that Apple deems private API. We made the changes to our code but forgot to update the cocoapods keys that Travis sets. This PR fixes that issue, hopefully. :)

Updates Travis’ cocoapods keys variable names

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Extensions/UINavigationItem.swift
Specs/Extensions/UINavigationItemSpec.swift
Specs/Model/NotificationAttributedTitleSpec.swift

iOS 10 is animating `rightBarButtonItems` when they're assigned during a pull-to-refresh on both Post Details and Profiles. Rather than reassigning the buttons on pull to refresh we'll show what's already there.
@colinta, this feels harmless enough to me, any negative side effects you can think of?
[fixes #131181209](https://www.pivotaltracker.com/story/show/131181209)

Don’t redraw rightBarButtonItems

---

Ello.xcodeproj/project.pbxproj
Resources/StubbedResponses/profile.json
Resources/StubbedResponses/users_user_details.json
Sources/Model/Profile.swift
Sources/Model/User.swift
Specs/Controllers/Profile/ProfileViewControllerSpec.swift
Specs/Helpers/Stubs.swift
Specs/Model/ProfileSpec.swift
Specs/Model/UserSpec.swift

*AND* moves a bunch of "should be in Profile" properties out of `User`, into `Profile`.
This should be merged into `cg/add/is_collaborateable`, since it uses changes from that branch.

Adds `hasAutoWatchEnabled` property to `Profile`

---

Sources/Controllers/Omnibar/OmnibarViewController.swift

Editing an existing comment was not updating the comment in streams, now it does.
This also fixes an issue where comment and post counts were getting increased every time a comment or post was edited.
[fixes #131642307](https://www.pivotaltracker.com/story/show/131642307)
Executed 2207 tests, with 0 failures (0 unexpected) in 323.502 (325.532) seconds

Fix comment editing rendering issues

---

Sources/Controllers/Search/SearchScreen.swift
Sources/Extensions/UIViewExtensions.swift
Specs/Extensions/UIViewExtensionsSpec.swift

Only used in the `SearchScreen` to avoid `if let`, but easily avoided by using local vars & `self.prop = prop`.

Removes `addToView` helper

---

Sources/Controllers/Stream/Cells/CategoryCardCell.swift

Was supposed to be `0.4`, this got lost when we fixed selection.

Fixes the category card black opacity

---

Sources/Controllers/Stream/StreamKind.swift

Not just in `Following/Starred` - and never from Post Detail.

Tapping text in grid should *always* opens detail

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Profile/Calculators/ProfileHeaderCellSizeCalculator.swift
Sources/Controllers/Profile/Calculators/ProfileStatsSizeCalculator.swift
Sources/Controllers/Profile/ProfileHeaderCompactView.swift
Sources/Controllers/Profile/Views/ProfileBaseView.swift
Sources/Controllers/Profile/Views/ProfileStatsView.swift
Sources/Controllers/Stream/CalculatedCellHeights.swift
Sources/Controllers/Stream/CellDequeing/CategoryCardCellPresenter.swift
Sources/Controllers/Stream/CellDequeing/NotificationCellPresenter.swift
Sources/Controllers/Stream/CellDequeing/ProfileHeaderCellPresenter.swift
Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
Sources/Controllers/Stream/CellDequeing/StreamTextCellPresenter.swift
Sources/Controllers/Stream/Cells/StreamImageCellSizeCalculator.swift
Sources/Controllers/Stream/Cells/StreamNotificationCellSizeCalculator.swift
Sources/Controllers/Stream/Cells/StreamTextCellSizeCalculator.swift
Sources/Controllers/Stream/StreamCellItem.swift
Sources/Controllers/Stream/StreamDataSource.swift
Specs/Controllers/Stream/StreamDataSourceSpec.swift
Specs/Controllers/Stream/StreamNotificationCellSizeCalculatorSpec.swift
Specs/Fakes/FakeProfileHeaderCellSizeCalculator.swift
Specs/Fakes/FakeStreamNotificationCellSizeCalculator.swift
Specs/Fakes/FakeStreamTextCellSizeCalculator.swift

Introduces `CalculatedCellHeights` struct to store all the calculated sizes.  Lots of red/green noise around this change.
Some refactors to constraints in `ProfileHeaderCompactView` (added `centerX` constraints, otherwise just moved some things around).
Fixed `ProfileBaseView` so that it doesn't call `privateInit` twice.

Implements the `ProfileHeaderCompactView` layout

---

Sources/Controllers/Profile/ProfileHeaderCell.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Profile/Views/ProfileNamesView.swift
Sources/Controllers/Profile/Views/ProfileStatsView.swift
Sources/Controllers/Stream/StreamViewController.swift

Posts/Following/Followers/Loves are wired up. `StreamViewController` no longer implements `ProfileHeaderResponder`, `ProfileViewController` is now in charge.

Profile Stats Button Events

---

Sources/Controllers/Profile/ProfileHeaderCell.swift
Sources/Controllers/Profile/Views/ProfileBioView.swift
Sources/Controllers/Profile/Views/ProfileLinksView.swift
Sources/Controllers/Stream/StreamDataSource.swift

Unfortunately we weren't easily able to use the responder chain in this case. `WebLinkDelegate` uses non Objective-C parameters in it's single function (`ElloAPI`). That prevents us from using a selector which must be exposed to Objective-C. Instead we're using the old `webLinkDelegate` pattern of assignment in `StreamDataSource` via a passthrough into both `ProfileBioView` and `ProfileLinksView`.

Wire up bio and links views to open external links

---

Ello.xcodeproj/project.pbxproj
Sources/AppDelegate.swift
Sources/Controllers/Categories/CategoryGenerator.swift
Sources/Controllers/Categories/CategoryProtocols.swift
Sources/Controllers/Categories/CategoryScreen.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Discover/DiscoverAllCategoriesViewController.swift
Sources/Controllers/Discover/DiscoverViewController.swift
Sources/Controllers/Stream/Cells/StreamCellType.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Networking/CategoryService.swift
Sources/Views/CategoryCardListView.swift
Sources/Views/Screens/StreamableScreen.swift
Sources/controllers/stream/Cells/ColumnToggleCell.swift

In order to get the "fetch all categories" request into the `CategoryViewController`, I added a protocol `CategoryStreamDestination` which extends `StreamDestination`.  It's a private var on `CategoryGenerator`, and the `destination` returns that object, cast as a `StreamDestination`.  The swift compiler isn't quite smart enough to see that `CategoryStreamDestination` *satisfies* the `StreamDestination` type requirement, so this little handshake is required there.  Not a big fan, I wish we could just use `var destination: CategoryStreamDestination?`, but oh well.
Once the categories are loaded, we check for "did the user scroll?", and if not it adjusts the content inset so that the grid/list toggle is hidden.  The toggle doesn't start out hidden, but that enhancement probably wouldn't be …

Adds categories card list view to CategoryViewController

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Profile/Categories/ProfileCategoriesViewController.swift
Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Model/Tracker.swift

Since "category opened" can also occur when tapping a `CategoryCardListView` button, there's a custom tracking event for that (`"category opened", {category: category.slug}`).

Adds Tracking events to category/category headers

---

Ello.xcodeproj/project.pbxproj
Resources/StubbedResponses/CustomResponses/category.json
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Discover/DiscoverAllCategoriesViewController.swift
Sources/Controllers/Profile/Categories/ProfileCategoriesViewController.swift
Sources/Controllers/Stream/Cells/CategoryListCell.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
Sources/Extensions/StringExtensions.swift
Sources/Networking/ElloAPI.swift
Specs/Controllers/Categories/CategoryGeneratorSpec.swift
Specs/Controllers/Stream/Cells/CategoryListCellSpec.swift

Deep linking to the new Category screens is setup. We may need to change this behavior pending feedback from Product but it at least functional.
The large number of lines is deceiving. Most of them come from `category.json`. Specs should pass this go around.

Support new category deep linking

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Stream/StreamKind.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
Sources/Utilities/DeepLinking.swift
Specs/Utilities/DeepLinkingSpec.swift

Primarily, this streamlines the handling of deeplinks as well as enabling deep linking onto the top of a new navigation controller stack (in ProfileCategories).

Category Header Tweaks

---

Sources/Controllers/Categories/CategoryViewController.swift

* Tapping on categories in the list nav was failing due to a local variable shadowing the class instance variable with the same name. 
* Selecting "Featured" failed on a force unrwap when creating a `DiscoverType`.

Fixes inability to tap on categories in list nav

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Categories/CategoryProtocols.swift
Sources/Controllers/Categories/CategoryScreen.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Views/CategoryCardListView.swift
Sources/Views/CategoryCardView.swift
Specs/Controllers/Categories/CategoryViewControllerSpec.swift

Meta categories page correctly when visited from Discover landing screen
[fixes #134596259](https://www.pivotaltracker.com/story/show/134596259)
Categories have a selected state in the horizontal category nav
[fixes #134596301](https://www.pivotaltracker.com/story/show/134596301)
Additionally, viewing a meta category from Discover scrolls to the correct navigation tile.

Fixes meta category paging & category selection

---

Sources/Controllers/Categories/CategoryProtocols.swift
Sources/Controllers/Categories/CategoryScreen.swift
Sources/Controllers/Categories/CategoryViewController.swift
Specs/Controllers/Categories/CategoryScreenSpec.swift
Specs/Controllers/Categories/CategoryViewControllerSpec.swift

Fixes the "double spinner" issue.

Hide pull-to-refresh while the category cards animate in

---

Sources/Controllers/Stream/StreamDataSource.swift
Specs/Controllers/Stream/StreamDataSourceSpec.swift

Removing the grid/list toggle changed our new post insertIndexPath in Following.

Inserts new posts correctly

---

Resources/Settings.storyboard
Sources/Controllers/AutoComplete/AutoComplete.swift
Sources/Controllers/AutoComplete/AutoCompleteCellPresenter.swift
Sources/Controllers/AutoComplete/AutoCompleteViewController.swift
Sources/Controllers/AutoComplete/AutoCompleteViewController.xib
Sources/Controllers/Omnibar/OmnibarScreenAutocomplete.swift
Sources/Controllers/Settings/SettingsViewController.swift
Sources/Model/AutoCompleteResult.swift
Sources/Networking/AutoCompleteService.swift
Sources/Networking/ElloAPI.swift
Sources/Networking/ElloAPIDescription.swift
Sources/Utilities/InterfaceString.swift
Sources/Views/ElloTextField.swift
Sources/Views/ElloTextFieldView.swift

When location results come in, they're "coerced" into `AutoCompleteResult` objects by setting `name` to the `location` value.  Not terribly intuitive (?) but maximizes code reuse.

Adds AutoCompleteViewController to Settings when Location changes

---

Sources/Controllers/Onboarding/CreateProfileProtocols.swift
Sources/Controllers/Onboarding/CreateProfileScreen.swift
Sources/Controllers/Onboarding/CreateProfileViewController.swift
Sources/Extensions/StringExtensions.swift
Sources/Model/User.swift
Sources/Networking/ReAuthService.swift
Sources/Utilities/Validator.swift
Specs/Controllers/Onboarding/CreateProfileScreenSpec.swift
Specs/Controllers/Onboarding/CreateProfileViewControllerSpec.swift
Specs/Extensions/StringExtensionSpec.swift
Specs/Utilities/ValidatorSpec.swift

Links are now validated on the client, and the user cannot continue if the link field is invalid, even if they entered other info.
Also discovered a bug where an existing user's links would not be displayed by the app if they deleted their bio.  The changes *are* saved, though, and it's only when updatind an existing user (would not affect onboarding).

Fixes onboarding links validation

---

Sources/Controllers/Notifications/NotificationsGenerator.swift
Sources/Controllers/Notifications/NotificationsViewController.swift

The tracking code was in the placeholders callback, not replace-items, and needed to be triggered on `viewDidAppear`

Fixes Announcement tracking

---

Sources/Controllers/Stream/StreamViewController.swift

Double tapping the post of a user with loves disabled is no longer allowed.
[Fixes #257 133266763](https://www.pivotaltracker.com/story/show/133266763)

Prevent double tap loves when disabled

---

Podfile
Podfile.lock
fastlane/Fastfile

A few dependencies were not locked down tightly enough. 
`ImagePickerSheetController` removed their `swift2.3-improvements` branch out from under us and `TimeAgoInWords` and `SVGKit` changed. `Podfile` now locks down to individual commits on those 3 pods.

Locks down dependencies

---

Sources/Controllers/Onboarding/CreateProfileViewController.swift
Sources/Model/Regions/Asset.swift
Sources/Model/User.swift
Sources/Networking/ProfileService.swift
Sources/Utilities/TemporaryCache.swift
Specs/Model/UserSpec.swift

The API returns `ello-default-*` image URLs, even after the user has uploaded images.  This fixes that by detecting those URLs after a successful upload, and replacing the default images with the S3 image URLs.

Fixes image uploads on new user

---

Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Notifications/NotificationsGenerator.swift
Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Views/ElloCollectionView.swift
Specs/Controllers/Stream/StreamViewControllerSpec.swift

Most of the logic changes are in `NotificationsViewController`, but all the Generator-based controllers were clearing the HUD in `setPlaceholders`, which meant the HUD was going away immediately since that callback is called immediately.
The `ElloCollectionView` code is being reverted, we already reverted it in swift3.0, it was meant to fix a minor bug, but causes an issue with pull-to-refresh.

Fixes to Notifications and other Stream loading/reloading

---

Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/StreamDataSource.swift

A bug we found in swift3 is also in 1.20; tapping on "Invite" has no effect (because of the `.onboardingInviteFriend` cell type).
Also figured out "scroll to last comment", so I backported that one, too.

Fixes onboarding invite and scroll-to-last-comment

---

Sources/Controllers/Profile/ProfileGenerator.swift
Sources/Controllers/Stream/Detail/PostDetailGenerator.swift

This allows content to "stick around" during a reload.  Tested in post detail and profile, reloading and infinite scroll.

Just like in notifications: only set placeholders on initial load

---

Sources/Controllers/Categories/CategoryGenerator.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/Stream/StreamViewController.swift

Double spinner was showing up on Post Detail, and also on the Category view.
If you tapped a post from notifications and refreshed it, the contentInsets were incorrect, I put in a simple fix for that (work around `SSPullToRefresh` overriding contentInset).

Fixes the double spinner, and another stab at the contentInsets bug

---

Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Model/ExperienceUpdate.swift

We were not preventing a user from reposting the same post twice which caused a crash on the second attempt.
For other actions, such as loving a post, the returned post in the api call has it's `loved` property set to true. Reposting is unique in that the API returns the new repost, not the updated original post. The result was reposted posts found in multiple streams were not updated correctly after reposting. 
This PR updates the reposted `Post` in `ElloLinkedStore` and posts a new experience update, `.reposted`.
[Fixes #288137191093](https://www.pivotaltracker.com/story/show/137191093)

Fix double reposting crash

---

Podfile
Podfile.lock
Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/Stream/StreamContainerViewController.swift
Specs/Controllers/Omnibar/OmnibarViewControllerSpec.swift
Specs/Controllers/Stream/PostbarControllerSpec.swift

Tapping red dot in Notifications shows the loader (regression fix), and in Streams tapping the red dot while viewing "Starred" will switch to "Following" and reload the page.

Changes behavior of red-dot reloading in Notifications and Streams

---

Sources/Controllers/Notifications/NotificationsScreen.swift
Sources/Controllers/Notifications/NotificationsViewController.swift

I started out fixing the `NotificationsScreen`, but switched to reusing the `positionNavBar` method instead.

Fixes status bar visibility on Notifications Screen

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/Stream/CellDequeing/StreamTextCellPresenter.swift
Sources/model/Regions/RegionKindStreamCellTypeAddition.swift
Specs/Model/Regions/RegionKindStreamCellTypeAdditionSpec.swift

TextRegion `|>` break up `<p>` tags `|>` break up `<br>` tags `|>` truncate to 7500 characters.
Wondering about the `7500 + 10` code?  It's to remove the very last `</p>`, if it's there (and maybe newlines - this is all a bit hand-wavy).

Truncates text regions even more

---

Sources/Controllers/Stream/Cells/StreamInviteFriendsCell.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/Stream/StreamableViewController.swift

Previously, we had `inviteDelegate` and `inviteResponder` protocols. One was implemented by `StreamableViewController`, the other by `StreamViewController`. Now that we're using the responder chain they can both be moved into `StreamableViewController`. A nice side effect that slims down `StreamViewController` a bit.

Combines inviteResponder and inviteDelegate

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/Profile/ProfileHeaderCell.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Search/SearchViewController.swift
Sources/Controllers/Settings/DynamicSettingsViewController.swift
Sources/Controllers/Stream/Cells/UserAvatarsCell.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Networking/ElloAPI.swift

This required a bit of work due to `@objc`'s inability to accept swift only types as arguments in `#selector`. The solution is to box swift's value types in a recognizable Objective-C class. A bit ugly but it does the trick.

SimpleStreamDelegate -> SimpleStreamResponder

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/ElloTabBarController.swift
Sources/Controllers/Join/JoinViewController.swift
Sources/Controllers/LoggedOut/LoggedOutViewController.swift
Sources/Controllers/Login/LoginViewController.swift
Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Onboarding/CreateProfileViewController.swift
Sources/Controllers/Onboarding/InviteFriendsViewController.swift
Sources/Controllers/Onboarding/OnboardingViewController.swift
Sources/Controllers/Profile/Categories/ProfileCategoriesViewController.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
Sources/Model/Regions/Asset.swift
Sources/Networking/ElloAPI.swift
Sources/Networking/ElloURI.swift
Sources/Utilities/ElloWebViewHelper.swift
Specs/Controllers/Stream/StreamViewControllerSpec.swift
Specs/Networking/AuthStateSpec.swift
Specs/Networking/ElloURISpec.swift

:v: Yay to centralized link handling!  Since `AppViewController` was already handling all the deep links, I wondered why we didn't rely on it within `StreamViewController`, too, and couldn't find a good reason.  Posts and Profiles are pushed onto the visible view controller.

Implements deep links in logged out views, and refactors OUT link handling from `StreamViewController`

---

Sources/Controllers/Search/SearchScreen.swift

The search screen logic for showing the "invite friends" button was flipped - saved by specs, actually!

Fixes SearchScreen

---

Sources/Controllers/Stream/StreamViewController.swift

@caseydoran noticed this in 1.21

Tracks 'screen event' after pull to refresh

---

Sources/Controllers/Notifications/NotificationsViewController.swift

I noticed this when I was verifying the pull-to-refresh tracking, that caused Notifications to be double-tracked.

Removes redundant tracking

---

Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/StreamContainerViewController.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Specs/Controllers/Stream/PostbarControllerSpec.swift
Specs/QuickExtensions.swift

This one is nifty for a few reasons. 1) It finally gets rid our long standing "// This is a bit dirty, we should not call a method on a compositionally held controller's createPostDelegate. Can this use the responder chain when we have parameters to pass?" comments. Yay. 2) Rather than assigning a delegate in specs we verify responder behavior by using a mock window that implements the responder functions. Not as elegant but cool that it works.

CreatePostDelegate -> CreatePostResponder

---

Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift

These are pretty small so I included both `CategoryResponder` and `SelectedCategoryResponder`. These compile and specs pass but it is unclear to me what causes `func collectionView(_ collectionView: UICollectionView, didDeselectItemAt indexPath: IndexPath)` in `StreamViewController` to be called. I was unable to trigger that callback through actual app use. Any ideas?

Category delegates -> responders

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/ElloNavigationController.swift
Sources/Controllers/LoggedOut/LoggedOutScreen.swift
Sources/Controllers/LoggedOut/LoggedOutViewController.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Relationship/RelationshipController.swift
Sources/Controllers/Stream/Cells/SearchStreamCell.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Sources/Utilities/FreeMethods.swift
Specs/Controllers/Relationship/RelationshipControlSpec.swift

Wherever a `currentUser` is required, pop up the 'join now' message instead.  See commits for more details.

Shows logged out message when user attempts interaction

---

Ello.xcodeproj/project.pbxproj
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Onboarding/CategoriesSelectionViewController.swift
Sources/Controllers/Profile/ProfileProtocols.swift
Sources/Controllers/Profile/ProfileScreen.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Relationship/BlockUserModalViewController.swift
Sources/Controllers/Relationship/RelationshipControl.swift
Sources/Controllers/Relationship/RelationshipController.swift
Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
Sources/Controllers/Stream/Cells/UserAvatarsCell.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/ResponderChainableController.swift
Sources/Controllers/Stream/StreamContainerViewController.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Sources/model/RelationshipPriority.swift
Specs/Controllers/Profile/ProfileViewControllerSpec.swift
Specs/Controllers/Relationship/BlockUserModalViewControllerSpec.swift
Specs/Controllers/Relationship/RelationshipControlSpec.swift
Specs/Controllers/Relationship/RelationshipControllerSpec.swift
Specs/Controllers/Stream/PostbarControllerSpec.swift

This was the most intricate of the conversions. The interplay between `RelationshipController`, `RelationshipControl` and their delegate/responders required a lot of Swift value type wrapping and code refactoring. `RelationshiopController` is now held by `BaseElloViewController` due to `BlockModalViewController`'s need for it to be in the responder chain.
Future work may include renaming the `RelationshipPriority` and `RelationshipRequestStatus` wrappers for more clarity.

Relationship Responders

---

Sources/Controllers/Notifications/AnnouncementCell.swift
Sources/Controllers/Notifications/NotificationCell.swift
Sources/Controllers/Profile/ProfileHeaderCell.swift
Sources/Controllers/Profile/Views/ProfileBioView.swift
Sources/Controllers/Profile/Views/ProfileLinksView.swift
Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
Sources/Controllers/Stream/Cells/StreamTextCell.swift
Sources/Controllers/Stream/StreamDataSource.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift
Sources/Networking/ElloURI.swift
Sources/Utilities/ElloWebViewHelper.swift
Specs/Controllers/Stream/StreamViewControllerSpec.swift
Specs/Utilities/ElloWebViewHelperSpec.swift

Straightforward enough except for the new `origin` argument to `ElloWebViewHelper.handle()` which allows `ElloWebViewHelper` to remain a static struct rather than implementing `UIResponder`.

WebLinkDelegate -> WebLinkResponder

---

Sources/Controllers/Settings/DynamicSettingCategoryViewController.swift
Sources/Controllers/Settings/DynamicSettingCell.swift
Sources/Controllers/Settings/DynamicSettingsViewController.swift
Sources/Controllers/Settings/SettingsViewController.swift
Specs/Controllers/Settings/DynamicSettingCellSpec.swift

Initially I was going to convert both `DynamicSettingCellDelegate` and `DynamicSettingsDelegate` but `DynamicSettingsDelegate` really should be a delegate so I reverted it. There wasn't an obvious way to get `SettingsViewController` into the responder chain for changes to dynamic setting category toggles.

DynamicSettingCellDelegate -> DynamicSettingCellResponder

---

Sources/Controllers/Stream/StreamDataSource.swift

This change is subtle. The bug this fixes is reproducible by editing a post that has comments. Once the `Post` is edited the comments no longer show up beneath the post on a post detail.
When editing a `Post` a `PostChangedNotification` is posted with a `ContentChange.replaced`. Semantically this means that the post has been replaced with a _new_ post. Replaced posts should not modify the comments on the post. This small change fixes that.
There is a chance that I've not thought of all the implications of this change. A second set of eyes would be helpful here @colinta. Can you think of any negative or unforeseen consequences of removing the `.replaced` `ContentChange` check here? In manual testing I verified correctness when deleting a post, deleting a comment, editing a post and editing …

Do not modify comments when a post is replaced

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/LoggedOut/LoggedOutViewController.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Relationship/RelationshipController.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Sources/Utilities/Tracker.swift

@caseydoran thoughts on the names of these events?  They don't match webapp, because the app behavior isn't the same (we don't open a registration modal).

Log tracking events depending on logged out event type

---

Sources/Controllers/Stream/StreamableViewController.swift
Sources/Controllers/WebBrowser/ElloWebBrowserViewController.swift

Unfortunately this is only a partial fix for both of these bugs. 👇 
[Fixes #139398397](https://www.pivotaltracker.com/story/show/139398397) & [Fixes #139473309](https://www.pivotaltracker.com/story/show/139473309)
When launching a native screen from an in-app browser  the screen did not have a nav bar, it does now **_but_** the status bar does not hide correctly when scrolling. Further tweaking is necessary but I felt it was better to get a 1.22 build ready than delay it for this relatively minor bug.
Additionally, the screen can be launched in landscape mode if the browser is in landscape. Rotating to portrait will lock the screen to portrait and prevent further rotation. Similar to the first bug, this is a partial fix. Better than before but also requiring additional attention.

Show navigation bar on native screens launched from browser

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/App/DebugTrackingController.swift
Sources/Controllers/ElloTabBarController.swift

We were looking at tracking data, and realized that `Screen AppViewController` and `Screen ElloTabBarController` events were in there, but they are just noise, so this prevents them from being tracked.

Tracking changes from Justin

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/Stream/CellDequeing/StreamFooterCellPresenter.swift
Sources/Controllers/Stream/StreamableViewController.swift

Logged out deep links now push onto a nested nav controller inside of `LoggedOutController` instead of getting pushed onto the nav controller that `LoggedOutController` is in.
[Fixes #138356797](https://www.pivotaltracker.com/story/show/138356797)

Fixes placement of deep links when logged out

---

Ello.xcodeproj/project.pbxproj

No more of this nonsense when running `pod install`:
```
[!] The `Ello [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Ello/Pods-Ello.debug.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
```

Fixes pod warnings

---

Sources/Controllers/Stream/PostbarController.swift

When logged out and when a post has zero comments, tapping the comment icon expands the signup footer.
[Fixes #140508347](https://www.pivotaltracker.com/story/show/140508347)
[Fixes #140508379](https://www.pivotaltracker.com/story/show/140508379)

Show signup footer when tapping comment icon

---

Sources/Controllers/ElloTabBarController.swift

Turns out that the simulator was not handling `UserDefaults` correctly. Setting a value and then reading the value immediately is not predictable in the simulator but is predictable on a device.
This PR simplifies reseting the tool tips for 2.0 by relying on a single `UserDefaults` variable, `ElloTab.ToolTipsResetForTwoPointOhKey`.
[Fixes #140820651](https://www.pivotaltracker.com/story/show/140820651)

Fixes rejected tooltip 2.0 story

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Categories/CategoryViewController.swift
Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/Onboarding/OnboardingViewController.swift
Sources/Controllers/Profile/ProfileViewController.swift
Sources/Controllers/Search/SearchViewController.swift
Sources/Controllers/Stream/Detail/PostDetailGenerator.swift
Sources/Controllers/Stream/Detail/PostDetailViewController.swift
Sources/Controllers/Stream/SimpleStreamViewController.swift
Sources/Controllers/Stream/StreamViewController.swift
Sources/Controllers/Stream/StreamableViewController.swift
Sources/Networking/ElloAPI.swift
Sources/Networking/ElloAPIDescription.swift
Sources/Networking/PostService.swift
Sources/Utilities/Tracker.swift
Specs/Networking/ElloAPISpec.swift

Adds `sendPostView` to PostDetailGenerator and `postView` endpoint to ElloAPI
`sendPostView` is only called if the post was loaded from memory, and not during a reload
postView is just one possible implementation of the `post_views` endpoint, and it
hard codes the values of `kind`.  In the future we could change it to support different
`post_views.kind` values.
Finishes [#140890503](https://www.pivotaltracker.com/story/show/140890503)

Tracks post detail page views when viewing a cached post

---

Sources/Extensions/ScreenExtensions.swift
Sources/Model/Regions/Asset.swift
Specs/Model/Regions/AssetSpec.swift

Single column streams on screens 768pts or wider now load the `xhdpi` asset url instead of the `hdpi` one. This gets us most of the way to full-width images on iPad. Further explorations in scaling are needed. They've been captured in the roadmap card https://trello.com/c/8SU0XRnV/263-improve-the-ios-app-experience-on-ipad.
[Finishes #140426449](https://www.pivotaltracker.com/story/show/140426449)

Loads xhdpi instead of hdpi on iPad

---

.travis.yml
Rakefile
Sources/model/Regions/RegionKindStreamCellTypeAddition.swift
Specs/Controllers/Stream/StreamDataSourceSpec.swift
Specs/Model/Regions/RegionKindStreamCellTypeAdditionSpec.swift

This was resulting in extra blank lines.  The downside is that if a user posts a
*really really* long post using `<br>` instead of `<p>`, that post will be
truncated.  The character limit is long, though: 7500.
Also added the `Staging*` keys to travis.

Removes the "convert <br> to TextRegion" feature

---

Sources/Views/NotificationBanner.swift
Specs/Model/Regions/AssetSpec.swift

By disabling `CRToast`, which is *odd*.

Getting specs to run faster

---

Rakefile
Sources/AppDelegate.swift
Sources/Controllers/App/AppViewController.swift
Sources/Controllers/App/DebugController.swift
Sources/Networking/APIKeys.swift
Sources/Networking/ElloURI.swift
Specs/Model/PostSpec.swift
Specs/Model/Regions/AssetSpec.swift
Specs/Model/Regions/ImageAttachmentSpec.swift
Specs/Networking/ElloURISpec.swift

**N.B.** I removed the `httpProtocol` and `domain` pair in favor of a combined `domain` that includes the protocol.  This was easier than having these separate, esp. since they were *never used separately*.
Your .env file should now look like this:
NINJA_CLIENT_KEY=[ninja key]
NINJA_CLIENT_SECRET=[ninja secret]
NINJA_DOMAIN=https://ninja
STAGE1_CLIENT_KEY=[stage1 key]
STAGE1_CLIENT_SECRET=[stage1 secret]
STAGE1_DOMAIN=https://stage1
STAGE2_CLIENT_KEY=[stage2 key]
STAGE2_CLIENT_SECRET=[stage2 secret]
STAGE2_DOMAIN=https://stage2
STAGING_SEGMENT_KEY=[staging segment key]
PROD_CLIENT_KEY=[prod key]
PROD_CLIENT_SECRET=[prod secret]
PROD_DOMAIN=https://ello.co
PROD_SEGMENT_KEY=[prod segment key]
Instead of toggling a debug server on/off, the user is presented with an alert that lets you …

Adds support for multiple debug servers

---

ShareExtension/ShareTrackerOverrides.swift
Sources/Extensions/ScreenExtensions.swift
Sources/Model/Regions/Asset.swift
Specs/Model/Regions/AssetSpec.swift

Non-retina iPads seem to crash at some point after loading a bunch of xhdpi images. Use hdpi instead of xhdpi on non-retina devices that are iPad width (>= 768).
[Fixes #141974207](https://www.pivotaltracker.com/story/show/141974207)
[Fixes #141973357](https://www.pivotaltracker.com/story/show/141973357)
[Fixes #141965649](https://www.pivotaltracker.com/story/show/141965649)
[Fixes #141965467](https://www.pivotaltracker.com/story/show/141965467)

Fix memory related crash on non-retina iPad

---

Sources/Controllers/Hire/HireScreen.swift
Sources/Controllers/Notifications/NotificationCell.swift
Sources/Controllers/Onboarding/CreateProfileScreen.swift
Sources/Controllers/Stream/Cells/CategoryCardCell.swift
Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
Sources/Controllers/Stream/Cells/StreamImageCell.swift
Sources/Extensions/UIImageViewExtensions.swift
Sources/Views/NarrationView.swift

make assignment shorter, support `InterfaceImage.Style`
closer to how `UIButton` assigns images.
[Finishes #142860715](https://www.pivotaltracker.com/story/show/142860715)

Refactor interface image assignment

---

Sources/Controllers/Stream/Cells/StreamCreateCommentCell.swift
Sources/Controllers/Stream/Cells/StreamFooterCell.swift
Sources/Controllers/Stream/Cells/StreamHeaderCell.swift
Sources/Controllers/Stream/PostbarController.swift
Sources/Controllers/Stream/StreamViewController.swift
Specs/Controllers/Stream/PostbarControllerSpec.swift

In order to accomplish this I had to "re-insert" the `StreamViewController` into the responder.  Easily done by adding a `properTarget(forAction:,withSender:)` to `PostbarController`.  This method starts the responder chain search at `StreamViewController` instead of `PostbarController`.
The `PostbarController` had a bit of schizophrenia going on whether to use `cell` or `indexPath`, so I refactored the code to prefer `cell`.  This also simplified the `StreamHeader/FooterCell` code.
[Finishes #142723269](https://www.pivotaltracker.com/story/show/142723269)

Fix tracking on related posts

---

Sources/AppDelegate.swift
Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
Sources/Controllers/Stream/Cells/CategoryHeaderCell.swift
Sources/Model/Category.swift
Sources/Model/PagePromotional.swift
Sources/Model/Regions/Asset.swift
Sources/Model/User.swift
Sources/Networking/AuthState.swift
Sources/Networking/ElloProvider.swift
Sources/Networking/Mapper.swift
Sources/Utilities/Preloader.swift

Decrease the memory pressure by using smaller avatars and category images.
The other code refactors were due to just poking around, trying different memory changes.
[Finishes #141965649](https://www.pivotaltracker.com/story/show/141965649)
[Finishes #143336577](https://www.pivotaltracker.com/story/show/143336577)

Use smaller images in more places

---

Ello.xcodeproj/project.pbxproj
Resources/GeneratedSVGs/arrow_normal.svg
Resources/GeneratedSVGs/arrow_selected.svg
Resources/GeneratedSVGs/arrow_white.svg
Sources/Controllers/App/DebugController.swift
Sources/Controllers/ElloTabBarController.swift
Sources/Controllers/Notifications/NotificationsViewController.swift
Sources/Controllers/Stream/FollowingViewController.swift
Sources/Controllers/Stream/StreamKind.swift
Sources/Networking/NewContentService.swift
Sources/Utilities/AppDefaults.swift
Sources/Utilities/InterfaceString.swift
Sources/Views/NewPostsButton.swift
Specs/Controllers/ElloTabBarControllerSpec.swift
Specs/Controllers/Notifications/NotificationsViewControllerSpec.swift
Specs/Controllers/Stream/FollowingViewControllerSpec.swift
Specs/Controllers/Stream/StreamKindSpec.swift
Specs/Networking/NewContentServiceSpec.swift
Specs/Utilities/GroupDefaultsSpec.swift

- added `NewPostsButton` class, updated `arrow.svg` to match comps (pulled in from Sketch, basically).
- shows on `newFollowingContent` notification
- hides on scroll-to-top
- tapping the button reloads `FollowingViewController`
Unrelated refactors:
- updated controllers and views to use `interfaceImage` setter (dunno why this wasn't in #386, I thought I had pulled these changes into that PR)
- `NewContentNotifications` use `()` instead of `Void?` as their value (removed `_ in` from listener blocks)
- fixed the notification listeners in `FollowingViewController`, they were not all being turned on and off.
- refactored `lastViewedCreatedAtKey` to be optional, and unique on a per-discover-endpoint basis (rather than based on `cacheKey`)
[Finishes …

Adds `More Posts` UI to Following

---

Sources/Controllers/Profile/ProfileViewController.swift

The grid/list toggle was also accidentally hidden.
[Finishes #141732301](https://www.pivotaltracker.com/story/show/141732301)

Adds 'share' button to logged out profiles

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/BaseElloViewController.swift
Sources/Controllers/Onboarding/InviteFriendsViewController.swift

Two things:
1. add 'close' button to invite
2. fix status bar when presenting an ello controller
The status bar show/hide code was only in `AppViewController`, which made sense, except when you present a controller *it* becomes the controller in charge of the status bar.
[Finishes #143987763](https://www.pivotaltracker.com/story/show/143987763)

Fixes Invite from Drawer (add close button)

---

Sources/Controllers/App/AppViewController.swift
Sources/Controllers/Categories/CategoryViewController.swift

The logic for how to show the category screen was poorly ported when we got rid of the "all categories screen". Fixed!
[Finishes #145043527](https://www.pivotaltracker.com/story/show/145043527)

Fixes deep links

---

Sources/Model/ArtistInviteSubmission.swift

Sorry, @alanpeabody!  We'll be able to remove this from the API in a couple months, once this version becomes ubiquitous.
[Finishes #151608677](https://www.pivotaltracker.com/story/show/151608677)

Remove unused 'statusChange' from ArtistInviteSubmission

---

Sources/Controllers/ArtistInvites/ArtistInvitesViewController.swift
Sources/Controllers/Editorials/EditorialsViewController.swift

If promos load first, which is often, there is just empty white space under the header.  This inserts a loader instead.

Show a spinner if promo header loads first

---

Sources/Controllers/Omnibar/OmnibarViewController.swift
Sources/Controllers/Profile/Views/ProfileLinksView.swift
Sources/Controllers/Settings/SettingsViewController.swift
Sources/Controllers/Stream/CellDequeing/NotificationCellPresenter.swift
Sources/Controllers/Stream/CellDequeing/StreamImageCellPresenter.swift
Sources/Controllers/Stream/Cells/PromotionalHeaderCell.swift
Sources/Model/Category.swift
Sources/Model/PagePromotional.swift
Sources/Model/User.swift
Sources/Networking/ProfileService.swift
Sources/Utilities/Preloader.swift
Sources/Views/CategoryCardView.swift
Specs/Controllers/Stream/Cells/NotificationCellSpec.swift
Specs/Extensions/UIWebViewSpecs.swift
Specs/Utilities/SafariActivitySpec.swift
Specs/Views/AvatarButtonSpec.swift

This requirement went away in swift 2 or 3

Remove all unnecessary references to 'as URL'
